### ISSUE TITLE
Renaming fails without root and in untitled files

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#1001]
An untitled file without a folder open (so the root is null)

```
[Error - 10:50:36 AM] Request textDocument/rename failed.
  Message: Value cannot be null.
Parameter name: path
  Code: -32000 
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Microsoft.Python.Core.IO.FileSystem.GetFiles(String path, String pattern, SearchOption option) in C:\Users\jabaile\python-language-server\src\Core\Impl\IO\FileSystem.cs:line 52
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.ScanClosedFiles(String name, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 86
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(String name, IPythonModule declaringModule, ILocatedMember rootDefinition, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 69
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(Uri uri, SourceLocation location, ReferenceSearchOptions options, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 62
   at Microsoft.Python.LanguageServer.Sources.RenameSource.RenameAsync(Uri uri, SourceLocation location, String newName, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\RenameSource.cs:line 36
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Rename(JToken token, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\LanguageServer.cs:line 290
```

And if I force the root to be an empty temporary directory:

```
[Error - 10:53:28 AM] Request textDocument/rename failed.
  Message: Invalid URI: The format of the URI could not be determined.
  Code: -32000 
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.<>c.<FindAllReferencesAsync>b__4_0(LocationInfo r) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 73
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(String name, IPythonModule declaringModule, ILocatedMember rootDefinition, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 72
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(Uri uri, SourceLocation location, ReferenceSearchOptions options, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\ReferenceSource.cs:line 62
   at Microsoft.Python.LanguageServer.Sources.RenameSource.RenameAsync(Uri uri, SourceLocation location, String newName, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Sources\RenameSource.cs:line 36
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Rename(JToken token, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\LanguageServer.cs:line 290
```

**Comment by jakebailey** [comment]
The former happens even in real files, so long as there is no root.
