### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-language-server#1003]
```
[Info  - 6:46:38 PM] Microsoft Python Language Server version 0.2.60.0
[Info  - 6:46:38 PM] Initializing for C:\Python37\python.exe
[Error - 7:30:33 PM] Request textDocument/completion failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Completion.TopLevelCompletion.GetCompletions(Node statement, ScopeStatement scopeStatement, CompletionContext context)
   at Microsoft.Python.LanguageServer.Completion.CompletionSource.GetCompletions(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)
```

**Comment by MikhailArkhipov** [comment]
Any particular scenario? Perhaps file was just opened so analysis is still empty?

**Comment by karthiknadig** [comment]
This happened immediately after opening a directory. But that is about as much info i can got. It has not happened again though.
