### ISSUE TITLE
Version 0.2.62 throwing exceptions on Mac

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#1008]
* OS Mac
* Python 2.7 and 3.7
* Throws number of exceptions, but LS still seems to be working.

```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.62.nupkg... complete
Unpacking archive... done
[Info  - 2:09:44 PM] GetCurrentSearchPaths /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python 
[Info  - 2:09:44 PM] Python search paths:
[Info  - 2:09:44 PM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/s2x0zzlx.t32
[Info  - 2:09:44 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7
[Info  - 2:09:44 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/lib-dynload
[Info  - 2:09:44 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 2:09:44 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 2:09:44 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 2:09:44 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 2:09:44 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 2:09:44 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/site-packages
[Info  - 2:09:44 PM] Configuration search paths:
[Info  - 2:09:44 PM]     /Users/don/Desktop/Development/vscode/ptvsd/src
[Info  - 2:09:45 PM] Microsoft Python Language Server version 0.2.62.0
[Info  - 2:09:45 PM] Initializing for /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python

Unhandled Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.<Start>b__25_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 2:09:47 PM] Connection to server got closed. Server will restart.
[Info  - 2:09:48 PM] GetCurrentSearchPaths /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python 
[Info  - 2:09:48 PM] Python search paths:
[Info  - 2:09:48 PM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/gtvsxjbr.p0s
[Info  - 2:09:48 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7
[Info  - 2:09:48 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/lib-dynload
[Info  - 2:09:48 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 2:09:48 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 2:09:48 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 2:09:48 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 2:09:48 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 2:09:48 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/site-packages
[Info  - 2:09:48 PM] Configuration search paths:
[Info  - 2:09:48 PM]     /Users/don/Desktop/Development/vscode/ptvsd/src
[Info  - 2:09:49 PM] Microsoft Python Language Server version 0.2.62.0
[Info  - 2:09:49 PM] Initializing for /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python

Unhandled Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.<Start>b__25_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 2:09:50 PM] Connection to server got closed. Server will restart.
[Info  - 2:09:51 PM] GetCurrentSearchPaths /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python 
[Info  - 2:09:52 PM] Python search paths:
[Info  - 2:09:52 PM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/yy5djrl5.ztw
[Info  - 2:09:52 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7
[Info  - 2:09:52 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/lib-dynload
[Info  - 2:09:52 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 2:09:52 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 2:09:52 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 2:09:52 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 2:09:52 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 2:09:52 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/site-packages
[Info  - 2:09:52 PM] Configuration search paths:
[Info  - 2:09:52 PM]     /Users/don/Desktop/Development/vscode/ptvsd/src
[Info  - 2:09:52 PM] Microsoft Python Language Server version 0.2.62.0
[Info  - 2:09:52 PM] Initializing for /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python

Unhandled Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.<Start>b__25_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 2:09:54 PM] Connection to server got closed. Server will restart.
[Info  - 2:09:55 PM] GetCurrentSearchPaths /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python 
[Info  - 2:09:55 PM] Python search paths:
[Info  - 2:09:55 PM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/dkxaym2r.h3k
[Info  - 2:09:55 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7
[Info  - 2:09:55 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/lib-dynload
[Info  - 2:09:55 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 2:09:55 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 2:09:55 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 2:09:55 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 2:09:55 PM]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 2:09:55 PM]     /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/lib/python2.7/site-packages
[Info  - 2:09:55 PM] Configuration search paths:
[Info  - 2:09:55 PM]     /Users/don/Desktop/Development/vscode/ptvsd/src
[Info  - 2:09:55 PM] Microsoft Python Language Server version 0.2.62.0
[Info  - 2:09:55 PM] Initializing for /Users/don/.local/share/virtualenvs/ptvsd-s4HZXZEa/bin/python
```

**Comment by AlexanderSher** [comment]
You got this on ptvsd?

**Comment by DonJayamanne** [comment]
it's a pipeenv environment.
When creating a python environment using pipeenv, the name of the folder is used. And the folder is ptvsd, hence the name ptvsd.

**Comment by MikhailArkhipov** [comment]
I think https://github.com/microsoft/python-language-server/pull/1036 should address this

**Comment by MikhailArkhipov** [comment]
@DonJayamanne - is it still a problem?

**Comment by MikhailArkhipov** [comment]
Closing for now, feel free to reopen if still problematic.
