### ISSUE TITLE
NullReferenceException getting URI absolute path in PythonModule.Definition

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#1018]
```
   at Microsoft.Python.Core.UriExtensions.ToAbsolutePath(Uri uri)
   at Microsoft.Python.Analysis.Modules.PythonModule.get_Definition()
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FromMember(IMember m)
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location, ILocatedMember& member)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)
```

```
   at Microsoft.Python.Core.UriExtensions.ToAbsolutePath(Uri uri)
   at Microsoft.Python.Analysis.Modules.PythonModule.get_Definition()
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FromMember(IMember m)
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location, ILocatedMember& member)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(Uri uri, SourceLocation location, ReferenceSearchOptions options, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.FindReferences(JToken token, CancellationToken cancellationToken)
```

Fix is likely one of:

- Just do `Uri?.ToAbsolutePath()`; `LocationInfo.FilePath` is only ever used for comparison and is allowed to be null.
- Pass in `PythonModule.FilePath` instead of converting `Uri`.

**Comment by AlexanderSher** [comment]
`Uri` can be null only for `SentinelModule`.

**Comment by AlexanderSher** [comment]
Do you have repro steps?

**Comment by jakebailey** [comment]
For `PythonModule`, you mean? I wonder where the null is coming from, then. Even for untitled files, there will be a URI. Without line information I've been assuming that the URI is null, but it might be a member (`Uri.LocalPath`?).

I have no repro for this, unfortunately; these are pulled from telemetry.

**Comment by AlexanderSher** [comment]
`LocalPath` doesn't return `null`. If `Uri` is null for any other type than `SentinelModule`, then we have a bug in some other place.

**Comment by MikhailArkhipov** [comment]
For `Sentinel` the `Module?.Analysis.Ast` would be null since it has empty analysis. Anyway, I'll add extra checks anyway.

**Comment by AlexanderSher** [comment]
How is it possible to get `Sentinel` in `FindDefinition`?

**Comment by MikhailArkhipov** [comment]
Unresolved import?

**Comment by AlexanderSher** [comment]
`FindDefinition` checks `analysis?.Ast` at the very beginning
```cs
            if (analysis?.Ast == null) {
                return null;
            }
```
So it won't proceed for unresolved import.

**Comment by MikhailArkhipov** [comment]
Bunch of code checks `FilePath` for nulls so I guess there could be cases.

**Comment by AlexanderSher** [comment]
`FilePath` can be null, `Uri` can't.
`SpecializedModule` is abstract, its only derived class is `TypingModule`. So that would require `TypingModule` to be created with null or invalid path.

**Comment by MikhailArkhipov** [comment]
Technically yes
```
            var import = CurrentPathResolver.GetModuleImportFromModuleName(name);
            var module = specializationConstructor(import?.ModulePath);
```
such as we didn't find `typing`

**Comment by MikhailArkhipov** [comment]
And in `PythonVariableModule`
```cs
public Uri Uri => Module?.Uri;
```

**Comment by AlexanderSher** [comment]
Then we should probably fail in this place: if module path isn't found, there is no reason to specialize it.

**Comment by MikhailArkhipov** [comment]
But this
```cs
        public PythonVariableModule(string name, IPythonInterpreter interpreter)
            : base(PythonMemberType.Module) {
            Name = name;
            Interpreter = interpreter;
            SetDeclaringModule(this);
        }
```
called from
```cs
        private PythonVariableModule GetOrCreateVariableModule(in string fullName, in PythonVariableModule parentModule, in string memberName) {
            if (_variableModules.TryGetValue(fullName, out var variableModule)) {
                return variableModule;
            }

            variableModule = new PythonVariableModule(fullName, Interpreter);
```
creates module with no `Module` and hence no URI

**Comment by AlexanderSher** [comment]
`PythonVariableModule` without `Module` means that it is actually a package. So we shouldn't get into searching for module members in first place.
