### ISSUE TITLE
CPU usage raise up to 100%+ after updated to the latest vscode

### ISSUE THREAD

**Issue by ivan706** [microsoft/python-language-server#1024]
It seams that this is a known issue, but the python-language-server works perfectly with old version of vscode.
After updated vscode yesterday, this issue appears......again......
cpu:
![image](https://user-images.githubusercontent.com/4433047/56949504-b12e9600-6b65-11e9-9711-d266d727180b.png)

OS: MAC 10.14.3
![image](https://user-images.githubusercontent.com/4433047/56949034-724c1080-6b64-11e9-9fc5-2379b076b906.png)

vscode: 1.33.1
![image](https://user-images.githubusercontent.com/4433047/56949068-83951d00-6b64-11e9-90fe-654309d2fcb5.png)

python-ext: 2019.4.11987
![image](https://user-images.githubusercontent.com/4433047/56949104-96a7ed00-6b64-11e9-802e-339aaf5b47fc.png)

**Comment by jakebailey** [comment]
Can you please give your language server version? It will be listed in the python output panel (the other versions are separate and likely not related as the LS is released separately).

https://github.com/Microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by ivan706** [comment]
> Can you please give your language server version? It will be listed in the python output panel (the other versions are separate and likely not related as the LS is released separately).
> 
> https://github.com/Microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

Starting Microsoft Python language server.
[Info  - 下午1:33:01] GetCurrentSearchPaths /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7 
[Info  - 下午1:33:01] Python search paths:
[Info  - 下午1:33:01]     /private/var/folders/1z/m9416s6150l81qwsftx5kcw40000gn/T/m4flpv1z.gjo
[Info  - 下午1:33:01]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7
[Info  - 下午1:33:01]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/lib-dynload
[Info  - 下午1:33:01]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 下午1:33:01]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 下午1:33:01]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 下午1:33:01]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 下午1:33:01]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 下午1:33:01]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/site-packages
[Info  - 下午1:33:01] Configuration search paths:
[Info  - 下午1:33:06] Microsoft Python Language Server version 0.2.63.0
[Info  - 下午1:33:06] Initializing for /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7
Process is terminating due to StackOverflowException.
[Info  - 下午6:39:57] Connection to server got closed. Server will restart.
[Error - 下午6:39:57] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:266956)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:267379)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午6:39:57] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:266956)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:267379)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午6:39:57] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:266956)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:267379)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午6:39:57] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:266956)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:267379)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 下午6:39:57] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:266956)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:267379)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Info  - 下午6:39:58] GetCurrentSearchPaths /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7 
[Info  - 下午6:39:58] Python search paths:
[Info  - 下午6:39:58]     /private/var/folders/1z/m9416s6150l81qwsftx5kcw40000gn/T/5ivyuuqr.3xw
[Info  - 下午6:39:58]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7
[Info  - 下午6:39:58]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/lib-dynload
[Info  - 下午6:39:58]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 下午6:39:58]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 下午6:39:58]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 下午6:39:58]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 下午6:39:58]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 下午6:39:58]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/site-packages
[Info  - 下午6:39:58] Configuration search paths:
[Info  - 下午6:40:02] Microsoft Python Language Server version 0.2.63.0
[Info  - 下午6:40:02] Initializing for /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7
Process is terminating due to StackOverflowException.
[Info  - 下午6:40:13] Connection to server got closed. Server will restart.
[Info  - 下午6:40:13] GetCurrentSearchPaths /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7 
[Info  - 下午6:40:13] Python search paths:
[Info  - 下午6:40:13]     /private/var/folders/1z/m9416s6150l81qwsftx5kcw40000gn/T/4ps3fmiw.vfd
[Info  - 下午6:40:13]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7
[Info  - 下午6:40:13]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/lib-dynload
[Info  - 下午6:40:13]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 下午6:40:13]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 下午6:40:13]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 下午6:40:13]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 下午6:40:13]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 下午6:40:13]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/site-packages
[Info  - 下午6:40:13] Configuration search paths:
[Info  - 下午6:40:15] Microsoft Python Language Server version 0.2.63.0
[Info  - 下午6:40:15] Initializing for /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7
Process is terminating due to StackOverflowException.
[Info  - 下午6:40:27] Connection to server got closed. Server will restart.
[Error - 下午6:40:27] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:111456)
	at Object.dispose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187437)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:187612)
	at module.exports.t.LanguageClient.handleConnectionClosed (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:253943)
	at t (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:185914)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at H (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:103786)
	at e.module.exports.e.invoke (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:217771)
	at e.module.exports.e.fire (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:218642)
	at t.module.exports.e.fireClose (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:263157)
	at Socket.<anonymous> (/Users/ivan/.vscode/extensions/ms-python.python-2019.4.11987/out/client/extension.js:1:264217)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Info  - 下午6:40:28] GetCurrentSearchPaths /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7 
[Info  - 下午6:40:28] Python search paths:
[Info  - 下午6:40:28]     /private/var/folders/1z/m9416s6150l81qwsftx5kcw40000gn/T/4hspalha.u5n
[Info  - 下午6:40:28]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7
[Info  - 下午6:40:28]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/lib-dynload
[Info  - 下午6:40:28]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 下午6:40:28]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 下午6:40:28]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 下午6:40:28]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 下午6:40:28]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 下午6:40:28]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/site-packages
[Info  - 下午6:40:28] Configuration search paths:
[Info  - 下午6:40:30] Microsoft Python Language Server version 0.2.63.0
[Info  - 下午6:40:30] Initializing for /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7
Process is terminating due to StackOverflowException.
[Info  - 下午6:40:41] Connection to server got closed. Server will restart.
[Info  - 下午6:40:42] GetCurrentSearchPaths /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7 
[Info  - 下午6:40:42] Python search paths:
[Info  - 下午6:40:42]     /private/var/folders/1z/m9416s6150l81qwsftx5kcw40000gn/T/kqv3ope5.hde
[Info  - 下午6:40:42]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7
[Info  - 下午6:40:42]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/lib-dynload
[Info  - 下午6:40:42]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
[Info  - 下午6:40:42]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
[Info  - 下午6:40:42]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
[Info  - 下午6:40:42]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
[Info  - 下午6:40:42]     /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
[Info  - 下午6:40:42]     /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/lib/python2.7/site-packages
[Info  - 下午6:40:42] Configuration search paths:
[Info  - 下午6:40:44] Microsoft Python Language Server version 0.2.63.0
[Info  - 下午6:40:44] Initializing for /Users/ivan/yotta/yottaweb-reform/yottaweb/venv/bin/python2.7
Process is terminating due to StackOverflowException.
[Error - 下午6:40:59] Connection to server got closed. Server will not be restarted.

**Comment by jakebailey** [comment]
0.2.63 is pretty old, the current release is 0.2.74 (the previous being 0.2.66). Can you reload VS Code to trigger an update and retry?

**Comment by ivan706** [comment]
> 0.2.63 is pretty old, the current release is 0.2.74 (the previous being 0.2.66). Can you reload VS Code to trigger an update and retry?

It seems OK after updated to version 0.2.82. Thanks a lot~~
