### ISSUE TITLE
NRE in PythonDictionary constructor

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/python-language-server#1046]
Reproducible on `numpy.ma.core` analysis.
```
   at Microsoft.Python.Analysis.Values.Collections.PythonDictionary..ctor(PythonDictionaryType dictType, IReadOnlyDictionary`2 contents, Boolean exact) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Values\Collections\PythonDictionary.cs:line 28
   at Microsoft.Python.Analysis.Types.Collections.PythonDictionaryType.CreateInstance(String typeName, IArgumentSet args) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Types\Collections\PythonDictionaryType.cs:line 31
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.CallOperator(PythonOperator op, IMember left, IPythonType leftType, IMember right, IPythonType rightType, Boolean tryLeft, Boolean tryRight) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.Operators.cs:line 211
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.GetValueFromBinaryOp(Expression expr) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.Operators.cs:line 158
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.GetValueFromExpression(Expression expr, LookupOptions options) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.cs:line 187
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.Walk(AssignmentStatement node) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 89
   at Microsoft.Python.Parsing.Ast.AssignmentStatement.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\AssignmentStatement.cs:line 45
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 37
   at Microsoft.Python.Parsing.Ast.IfStatementTest.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\IfStatementTest.cs:line 41
   at Microsoft.Python.Parsing.Ast.IfStatement.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\IfStatement.cs:line 45
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 37
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.Evaluate() in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 79
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.EvaluateScope(ScopeStatement target) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 79
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.ProcessClassBody() in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 110
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.EvaluateClass() in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 69
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.Evaluate() in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 34
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.Evaluate(ScopeStatement target) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 88
   at Microsoft.Python.Analysis.Analyzer.ModuleWalker.Walk(ClassDefinition node) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\ModuleWalker.cs:line 185
   at Microsoft.Python.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\ClassDefinition.cs:line 140
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\SuiteStatement.cs:line 37
   at Microsoft.Python.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in C:\GitHub\python-language-server\src\Parsing\Impl\Ast\PythonAst.cs:line 83
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 346
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode`1 node, AsyncCountdownEvent ace, Stopwatch stopWatch) in C:\GitHub\python-language-server\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 280
```

Issue caused by `ExpressionEval.CallOperator` calling `rightType.Call(rpi, swappedFuncName, new ArgumentSet(new[] { left }));`

**Comment by jakebailey** [comment]
Fails because:

```csharp
        // Constructor call
        public override IMember Call(IPythonInstance instance, string memberName, IArgumentSet args)
            => CreateInstance(Name, args);
```

The operator code expects that when you do `Call`, it does what the docs say:

```csharp
        /// <summary>
        /// Invokes method or property on the specified instance.
        /// </summary>
        /// <param name="instance">Instance of the type.</param>
        /// <param name="memberName">Member name to call, if applicable.</param>
        /// <param name="argSet">Call arguments.</param>
        IMember Call(IPythonInstance instance, string memberName, IArgumentSet argSet);
```

But none of our custom collection types defer these calls to the builtins.
