### ISSUE TITLE
Language Server lints but it does not provide Completions, go-to-definition nor hover functionalities

### ISSUE THREAD

**Issue by andfoy** [microsoft/python-language-server#1171]
After installing the latest python-language-server plugin through VSCode Marketplace, the plugin stops working partially. While pyflakes linting is available, the server fails attending ``textDocument/definition``, ``textDocument/completion`` and ``textDocument/hover`` requests.

When opening the output log from the server on the VSCode logging console, the following error appears, which seem to be related with some C# package that cannot be loaded.

```
Exception in IntelliCode extension for Microsoft Python Language Server: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Cryptography.Csp, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Security.Cryptography.Csp, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.PythonTools.Analysis.Pythia.PythiaModelLoader.LoadModelAsync(String modelPath, PythiaModel& sequenceModel)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(CompletionItemEx[] completionList, PythonAst ast, SourceLocation location, Int32 recommendataionLimit, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtension.HandleCompletionAsync(IDocumentAnalysis analysis, SourceLocation location, CompletionItemEx[] completionList, CancellationToken token)
```

**Comment by MikhailArkhipov** [comment]
This looks like intellicode extension rather than the LS itself. I will report it to the IC team internally.

**Comment by MikhailArkhipov** [comment]
You may try and uninstall IntelliCode extension if this happens consistently.

**Comment by andfoy** [comment]
@MikhailArkhipov Thanks for your help, actually, uninstalling the IntelliCode extension fixes this issue.

**Comment by vivlimmsft** [comment]
Hi @andfoy, sorry that you encountered this issue. I'd like to understand what the problem is so we can fix it.

Which OS are you using?
Which version of the language server do you have? (you can find it listed in the Python output window).

Could you please provide a hash of the file `~\.vscode\extensions\ms-python.python-2019.5.18678\languageServer.*\System.Security.Cryptography.Csp.dll`?

**Comment by andfoy** [comment]
> Which OS are you using?

I'm using Ubuntu 18.04

> Which version of the language server do you have?

Microsoft Python Language Server version 0.2.87.0

> Could you please provide a hash of the file

```bash
sha256sum ~/.vscode-insiders/extensions/ms-python.python-2019.5.18678/languageServer.0.2.87/System.Security.Cryptography.Csp.dll 

10dfd72033dca5cbdeccc17a42785b1784eb047c254205246011d329114bf988
```

**Comment by MikhailArkhipov** [comment]
What specifically fails in `textDocument/hover` and `textDocument/definition`? IC only participates in completion and even if throws an exception, it is handled.

**Comment by andfoy** [comment]
A dialog with the text ``Code analysis in progress...`` appears but the client does not return any completion options, neither enables definitions

**Comment by dainman** [comment]
I am seeing the same dialog on hover and then on Go to definition I get "no definition found for ..."

code version is 1.35
python language server 0.2.96

**Comment by MikhailArkhipov** [comment]
Well it may or may not be same issue. This case is open about intellicode exception
`at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync`. If you don't see any of that, please open separate issue, give a code snippet with imports or specific library you are unable to navigate to.

**Comment by jaredcm** [comment]
I'm seeing the same. 
Code version Version 1.36.0-insider
Python language server 0.2.96.0

I'm using pth files that point to the parent directory of my modules. Which allows for my modules to be resolvable by the python interpreter without messing with the search path at runtime. With the path files enabled, analysis hangs. When I remove the pth files (additional search paths) analysis completes, with the downside that my environment is broken and none of my custom module imports are resolvable. Is there a way for VSCode to ignore the workspace paths?  It only adds issues to my configuration since everything I need to resolve is resolved via the standard search paths.

### With PTH files ###
Starting Microsoft Python language server.
[Info  - 4:10:33 PM] Analysis cache path: /Users/{user}/Library/Caches/Microsoft/Python Language Server
[Info  - 4:10:33 PM] GetCurrentSearchPaths /Users/{user}/.pyenv/versions/3.7.2/bin/python 
[Info  - 4:10:33 PM] Python search paths:
[Info  - 4:10:33 PM]     /private/var/folders/9q/mshp41rj5419tdv0ftt4bz380000gn/T/csjquz0g.ng0
[Info  - 4:10:33 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7
[Info  - 4:10:33 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload
[Info  - 4:10:33 PM]     /Users/{user}/.local/lib/python3.7/site-packages
[Info  - 4:10:33 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/site-packages
[Info  - 4:10:33 PM]     /Users/{user}/Documents/Code/stress_test/tests
[Info  - 4:10:33 PM]     /Users/{user}/Documents/Code/stress_test/lib
[Info  - 4:10:33 PM]     /Users/{user}/Documents/Code/stress_test
[Info  - 4:10:33 PM]     /Users/{user}/Documents/Code/stress_test/unit_tests
[Info  - 4:10:33 PM] Configuration search paths:
[Info  - 4:10:34 PM] Microsoft Python Language Server version 0.2.96.0
[Info  - 4:10:34 PM] Initializing for /Users/{user}/.pyenv/versions/3.7.2/bin/python
Opening document file:///Users/{user}/Documents/Code/stress_test/lib/py_mod/identity/directory.py
_Analysis of lib.py_mod.identity.directory(Library) queued_ <- **This is resolvable via python as py_mod.identity.directory**
**End of output**

### Without PTH files ###
Starting Microsoft Python language server.
[Info  - 4:18:02 PM] Analysis cache path: /Users/{user}/Library/Caches/Microsoft/Python Language Server
[Info  - 4:18:02 PM] GetCurrentSearchPaths /Users/{user}/.pyenv/versions/3.7.2/bin/python 
[Info  - 4:18:03 PM] Python search paths:
[Info  - 4:18:03 PM]     /private/var/folders/9q/mshp41rj5419tdv0ftt4bz380000gn/T/etnqbc53.kch
[Info  - 4:18:03 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7
[Info  - 4:18:03 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload
[Info  - 4:18:03 PM]     /Users/{user}/.local/lib/python3.7/site-packages
[Info  - 4:18:03 PM]     /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/site-packages
[Info  - 4:18:03 PM] Configuration search paths:
[Info  - 4:18:03 PM] Microsoft Python Language Server version 0.2.96.0
[Info  - 4:18:03 PM] Initializing for /Users/{user}/.pyenv/versions/3.7.2/bin/python
Opening document file:///Users/{user}/Documents/Code/stress_test/lib/py_mod/identity/directory.py
Analysis of lib.py_mod.identity.directory(User) queued
Import:  __future__ /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/__future__.py 
Analysis of __future__(Stub) queued
Import:  mypy_extensions /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/site-packages/mypy_extensions.py 
Analysis of mypy_extensions(Stub) queued
Analysis of __future__(Library) queued
Import:  requests /Users/{user}/.pyenv/versions/3.7.2/lib/python3.7/site-packages/requests/__init__.py 
Analysis of sys(Stub) queued
Analysis of types(Stub) queued
...
Analysis of requests.models(Library) completed in 5.1125 ms.
_Analysis of lib.py_mod.identity.directory(User) completed in 5.6981 ms._ 
_Analysis complete: 646 modules in 3216.7447 ms._
_Analysis version 941 of 448 entries has been completed in 603.3527 ms._
**End of output**

**Comment by MikhailArkhipov** [comment]
@jaredcm, please open separate issue. PTH (which are not actually supported yet per https://github.com/microsoft/python-language-server/issues/537) are not related to specific exception menthioned here. Thanks.

**Comment by jaredcm** [comment]
@MikhailArkhipov I've put an update in #537.

**Comment by Ai-Himmel** [comment]
same issue
host: Windows 10 19041
code version: 1.42.1
Python Language Server: 0.5.30.0
Visual Studio IntelliCode: 1.2.5
```
Exception in IntelliCode extension for Microsoft Python Language Server: System.Security.Cryptography.CryptographicException: The input data is not a complete block.
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaModelLoader.LoadModelAsync(String modelPath, PythiaModel& sequenceModel)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.<>c__DisplayClass7_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(CompletionItemEx[] completionList, PythonAst ast, SourceLocation location, Int32 recommendataionLimit, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtension.HandleCompletionAsync(IDocumentAnalysis analysis, SourceLocation location, CompletionItemEx[] completionList, CancellationToken token)
```
