### ISSUE TITLE
lsp-request: Object reference not set to an instance of an object with lsp-ui-peek-find-references

### ISSUE THREAD

**Issue by vv111y** [microsoft/python-language-server#1317]
# Issue
When running ```lsp-ui-peek-find-reference``` on any token in a source file I get above error.

# Environment
- Spacemacs: 0.300.0@26.2
- emacs:  GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12
- This repo:  commit 4a261428ac3f6eadea3b208c91ae8e1b612a838c  
- python runtime: 3.6.7 64-bit

**Comment by jakebailey** [comment]
We're probably going to need more information than that; since this isn't VS Code, it'd be helpful for you to provide the request that emacs is making, as well as the full exception message with line numbers to know what's null and shouldn't be.

**Comment by yyoncho** [comment]
Here it is a callstack from the server side:

```
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.ScanClosedFiles(String name, CancellationToken cancellationToken) in /home/kyoncho/Sources/dotnet/python-language-server/src/LanguageServer/Impl/Sources/ReferenceSource.cs:line 123
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(String name, IPythonModule declaringModule, ILocatedMember rootDefinition, SourceLocation location, DefinitionSource definitionSource, CancellationToken cancellationToken) in /home/kyoncho/Sources/dotnet/python-language-server/src/LanguageServer/Impl/Sources/ReferenceSource.cs:line 72
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(Uri uri, SourceLocation location, ReferenceSearchOptions options, CancellationToken cancellationToken) in /home/kyoncho/Sources/dotnet/python-language-server/src/LanguageServer/Impl/Sources/ReferenceSource.cs:line 64
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.FindReferences(JToken token, CancellationToken cancellationToken) in /home/kyoncho/Sources/dotnet/python-language-server/src/LanguageServer/Impl/LanguageServer.cs:line 245
```

I did some investigation and the issue is caused that for some reason `ReadTextWithRetry` is failing the temp files that are created by Emacs. We could investigate what is causing that issue or alternatively make the `*.py` scan pattern configurable.  Let me know what do you think.

**Comment by jakebailey** [comment]
Can you provide some sample filenames? We can ignore them, but we can't avoid looking through unopened files when searching for references.

To me, I'd be curious as to why this would fail with an null ref anyway. My first impression would be that the temp files shouldn't be read and cause some IO error, but we catch those.

**Comment by MikhailArkhipov** [comment]
Probably needs null check on `content` since `ReadTextWithRetry` can return null.

**Comment by vv111y** [comment]
Project filenames? If I understand you right here's a sample
```
Batch.py
batchwrapper.py
Beam.py
Embed.py
floyd.yml
Layers.py
Models.py
Optim.py
Process.py
README.md
start_here.ipynb
start_here.md
starthere.org
Sublayers.py
TODOs.org
Tokenize.py
train.py
translate.py
```
In case it is worth anything, here is a lsp-log file
https://gist.github.com/df0054dd5b5b38395b3e0ffa11d3f6d2

**Comment by jakebailey** [comment]
Of the temp files, I mean.

**Comment by vv111y** [comment]
I am not familiar with that. What would I be looking for?

**Comment by jakebailey** [comment]
It's probably the null check, but I had assumed that since you determined that it was emacs temp files causing the issue in ScanClosedFiles and suggested modifying `*.py`, you knew what the files were called.

**Comment by jakebailey** [comment]
Oh dear, I didn't realize there were two people here, not just one, sorry!

**Comment by vv111y** [comment]
Can this be reopened? It is happening again

**Comment by MikhailArkhipov** [comment]
This project is not in active development. If you are using VS Code, you try Pylance language server.
