### ISSUE TITLE
AF: Library module of type Stub has been analyzed already!

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/python-language-server#1455]
Occasional AF in debug. Happens in master as well. Probably fallout of enabling of more module types to have library analysis. May relate to #1345 and #907.
```
[8/16/2019 4:33:06.982 PM Error] The active test run was aborted. Reason: Test host process crashed : Assertion Failed
Assertion Failed
Assertion Failed
Library module atexit of type Stub has been analyzed already!
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.IsValidVersion(Int32 version, IPythonModule& module, PythonAst& ast) in C:\PLS-Main\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerEntry.cs:line 116
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode`1 node, AsyncCountdownEvent ace, Stopwatch stopWatch) in C:\PLS-Main\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 256
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.<>c__DisplayClass34_0.<StartAnalysis>b__0() in C:\PLS-Main\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 244
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
```

**Comment by MikhailArkhipov** [comment]
Still happens unfortunately.

**Comment by MikhailArkhipov** [comment]
After some improvements in `db` this went away. Could be a temporary bug.

**Comment by MikhailArkhipov** [comment]
It's back
