### ISSUE TITLE
IndexManager.WorkspaceFiles returns paths rooted by cwd instead of workspace root

### ISSUE THREAD

**Issue by huguesv** [microsoft/python-language-server#1512]
Causes errors like this, notice the file path:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not find file 'C:\Projects\GitHub\Microsoft\python-language-server\output\bin\Debug\PythonApplication7.py'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Python.Core.IO.FileSystem.FileOpen(String path, FileMode mode, FileAccess access, FileShare share) in C:\Projects\GitHub\Microsoft\python-language-server\src\Core\Impl\IO\FileSystem.cs:line 35

```

See how my `_workspaceRootPath` is properly set, and also the `cwd` which I've added FYI.

![image](https://user-images.githubusercontent.com/1696845/64290828-b341a080-cf1b-11e9-8300-1e836f1670d5.png)

And now the result, which is incorrectly rooted:

![image](https://user-images.githubusercontent.com/1696845/64290860-c3f21680-cf1b-11e9-9816-efeb46b9b02e.png)

Problem seems to be in `DirectoryInfoProxy` class:
```
        public IEnumerable<IFileSystemInfo> EnumerateFileSystemInfos(string[] includePatterns, string[] excludePatterns) {
            var matcher = GetMatcher(includePatterns, excludePatterns);
            PatternMatchingResult matchResult = SafeExecuteMatcher(matcher);
            return matchResult.Files.Select((filePatternMatch) => {
                var path = PathUtils.NormalizePath(filePatternMatch.Path);
                return CreateFileSystemInfoProxy(new FileInfo(path));
            });
        }
```

The `FileInfo` is created with just the file name.

If I change that line to this, it works fine:
```
return CreateFileSystemInfoProxy(new FileInfo(Path.Combine(_directoryInfo.FullName, path)));
```

**Comment by jakebailey** [comment]
My wild guess is that VS Code starts the LS with the working directory set to the workspace, so we wouldn't have hit this until now.

**Comment by CTrando** [comment]
It might be slightly hard to test because we mock enumerating the file results, but we’re open to PRs if you want to contribute!
