### ISSUE TITLE
InvalidOperationException in DocumentBuffer.Update on didChange

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1651]
Seeing this a lot in the list:

```
   at Microsoft.Python.Core.Diagnostics.Check.InvalidOperation(Boolean condition, String message) in E:\A\_work\2\s\src\Core\Impl\Diagnostics\Check.cs:line 86
   at Microsoft.Python.Analysis.Documents.DocumentBuffer.Update(IEnumerable`1 changes) in E:\A\_work\2\s\src\Analysis\Ast\Impl\Documents\DocumentBuffer.cs:line 72
   at Microsoft.Python.Analysis.Modules.PythonModule.Update(IEnumerable`1 changes) in E:\A\_work\2\s\src\Analysis\Ast\Impl\Modules\PythonModule.cs:line 315
   at Microsoft.Python.LanguageServer.Implementation.Server.DidChangeTextDocument(DidChangeTextDocumentParams params) in E:\A\_work\2\s\src\LanguageServer\Impl\Implementation\Server.Documents.cs:line 36
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidChangeTextDocument(JToken token, CancellationToken cancellationToken) in E:\A\_work\2\s\src\LanguageServer\Impl\LanguageServer.cs:line 132
```

**Comment by jakebailey** [comment]
This is happening on 0.4.57, which is pretty recent. Line 72 doesn't make any sense, as it's after both of the checks.
