### ISSUE TITLE
Crash when running under Sublime Text (.NET Core Host has stopped working)

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/python-language-server#1682]
Hello!

I've cloned the latest commit (`fc99189`) and built according to instructions, if only a Release configuration instead of Debug (`dotnet build -c Release`). 

My `dotnet --version` = `3.0.100`

Now, trying to use the server in Sublime Text.

Did everything as per `Using_in_sublime_text.md`, but everytime I enable the `mspyls`, the server would crash after `mspyls enabled, starting server...` is shown in ST's status bar. The message is "**.NET Core Host has stopped working**".

WinDbg reveals the `CLR exception - code e0434352`, but that turns out to be just a generic CLR exception code, so I checked the event log for a more detailed description:
```
Application: dotnet.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Microsoft.Python.LanguageServer.Indexing.MostRecentDocumentSymbols.WorkAndSetTcs(Func`2 asyncWork) in C:\python-language-server\src\LanguageServer\Impl\Indexing\MostRecentDocumentSymbols.cs:line 63
   at Microsoft.Python.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__4_0(Object s) in C:\python-language-server\src\Core\Impl\Extensions\TaskExtensions.cs:line 85
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
I'm on Windows 7 x64, Sublime Text 3.2.2 b3211, LSP 0.9.0

**Comment by jakebailey** [comment]
More from #1661, I think.

**Comment by MikhailArkhipov** [comment]
Sort of. Worked before b/c token was never disposed of which leaks unmanaged objects: https://stackoverflow.com/questions/6960520/when-to-dispose-cancellationtokensource. Need to move dispose elsewhere (most probably hit via `WaitingForWork`).

**Comment by mitsukuri** [comment]
Mikhail, I've tried `dbf7357`, alas, it still crashes:
```
Application: dotnet.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Microsoft.Python.LanguageServer.Indexing.MostRecentDocumentSymbols.WorkAndSetTcs(Func`2 asyncWork) in C:\python-language-server-dbf7357e04b88ebdb01468af8639f6463cccda21\src\LanguageServer\Impl\Indexing\MostRecentDocumentSymbols.cs:line 63
   at Microsoft.Python.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__4_0(Object s) in C:\python-language-server-dbf7357e04b88ebdb01468af8639f6463cccda21\src\Core\Impl\Extensions\TaskExtensions.cs:line 85
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by mitsukuri** [comment]
Well, this is embarrassing, trying this half a day later and it seems to be working. Sorry for misleading you.

**Comment by MikhailArkhipov** [comment]
It might be broken, this is timing/threading issue. Depends on machine speed, number of cores, etc.

**Comment by jakebailey** [comment]
@mitsukuri Since you seem to have built it, does #1684 work out for you? This PR should be more consistent.

**Comment by mitsukuri** [comment]
@jakebailey, yep, #1684 seems to have fixed that. Holding my fingers crossed though)
