### ISSUE TITLE
NRE in MissingImportCodeActionProvider.GetAllVariables

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1769]
```
   at Microsoft.Python.LanguageServer.CodeActions.MissingImportCodeActionProvider.GetAllVariables(IDocumentAnalysis analysis) in E:\A\_work\3\s\src\LanguageServer\Impl\CodeActions\MissingImportCodeActionProvider.cs:line 595
   at Microsoft.Python.LanguageServer.CodeActions.MissingImportCodeActionProvider.CollectCandidates(ModuleInfo moduleInfo, String name, Dictionary`2 importFullNameMap, CancellationToken cancellationToken) in E:\A\_work\3\s\src\LanguageServer\Impl\CodeActions\MissingImportCodeActionProvider.cs:line 500
   at Microsoft.Python.LanguageServer.CodeActions.MissingImportCodeActionProvider.CollectCandidates(ModuleInfo moduleInfo, String name, Dictionary`2 importFullNameMap, CancellationToken cancellationToken) in E:\A\_work\3\s\src\LanguageServer\Impl\CodeActions\MissingImportCodeActionProvider.cs:line 543
   at Microsoft.Python.LanguageServer.CodeActions.MissingImportCodeActionProvider.GetCodeActionsAsync(IDocumentAnalysis analysis, Diagnostic[] diagnostics, Input input, List`1 codeActions, Ca
```

Based on the line number (and other similar checks), `analysis.GlobalScope.Variables` needs to be `analysis?.GlobalScope?.Variables`.

cc @heejaechang

**Comment by heejaechang** [comment]
thank you. let me send PR.

**Comment by jakebailey** [comment]
Sent one already at #1770 for you to look at. Can't use the null coalescing, since it combines poorly with out vars, but it's close.
