### ISSUE TITLE
ArgumentNullException in MemberEvaluator/FunctionEvaluator

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1793]
```
   at Microsoft.Python.Analysis.Analyzer.Symbols.MemberEvaluator..ctor(ExpressionEval eval, ScopeStatement target) in E:\A\_work\1\s\src\Analysis\Ast\Impl\Analyzer\Symbols\MemberEvaluator.cs:line 27
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator..ctor(ExpressionEval eval, PythonFunctionOverload overload) in E:\A\_work\1\s\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 41
   at Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddOverload(FunctionDefinition fd, IPythonClassMember function, Action`1 addOverload) in E:\A\_work\1\s\src\Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 161
   at Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddFunction(FunctionDefinition fd, PythonType declaringType) in E:\A\_work\1\s\src\Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 136
   at Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddFunctionOrProperty(FunctionDefinition fd) in E:\A\_work\1\s\src\Analysis\Ast\Impl\Analyzer\Symbol
```

`target` is null, so `overload.FunctionDefinition` is null, which comes from a `GetAstNode` call depending on `AddAstNode` during the overload's construction.

**Comment by MikhailArkhipov** [comment]
Also
```cs
_function = overload.ClassMember ?? throw new NullReferenceException(nameof(overload.ClassMember));
```
looks fishy.

**Comment by MikhailArkhipov** [comment]
My suspicion is that while analysis was running the module was updated and `Parse` cleared the AST map.

**Comment by MikhailArkhipov** [comment]
#1804
