### ISSUE TITLE
DllNotFoundException Crash

### ISSUE THREAD

**Issue by FrederickGeek8** [microsoft/python-language-server#1820]
## Environment data
- Language Server version: Microsoft Python Language Server version 0.4.114.0   
- OS and version: macOS 10.15.1
- Python version: 3.7.4 through `pyenv`

## Expected behaviour
The Python Language Server successfully starts and analyzes my Python project.

## Actual behaviour
The Python Language Server crashes with errors `System.DllNotFoundException: Unable to load shared library 'libproc' or one of its dependencies.`

## Logs

You can find the full trace log [here](https://gist.github.com/FrederickGeek8/d9cd657aae33f95e3997cacd5d28ac8f)

**EDIT:** This was a crash I recorded when testing a file `crash.py` with contents `import json`.

```
System.DllNotFoundException: Unable to load shared library 'libproc' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibproc, 1): image not found
   at Interop.libproc.proc_pidinfo(Int32 pid, Int32 flavor, UInt64 arg, proc_taskallinfo* buffer, Int32 bufferSize)
   at Interop.libproc.GetProcessInfoById(Int32 pid)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_PrivateMemorySize64()
   at Microsoft.Python.LanguageServer.Implementation.Server.OnAnalysisComplete(Object sender, AnalysisCompleteEventArgs e) in E:\A\_work\3\s\src\LanguageServer\Impl\Implementation\Server.Telemetry.cs:line 37
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.RaiseAnalysisComplete(Int32 moduleCount, Double msElapsed) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 235
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.StartAsync() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 168
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.StartNextSession(Task task) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzer.cs:line 310
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__4_0(Object s) in E:\A\_work\3\s\src\Core\Impl\Extensions\TaskExtensions.cs:line 89
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## Code Snippet / Additional lnformation
This bug occurs when editing most of my Python projects. However, this does not always occur. For example:
```python
import json
```
and
```python
import requests
```
crash, but 
```python
import math
```
does not.

**EDIT:** This error has only started to occur recently, though I can't pinpoint when.

**Comment by jakebailey** [comment]
Looks like dotnet/corefx#25157. Did you do an OS upgrade, maybe to Catalina?

**Comment by FrederickGeek8** [comment]
I saw that issue but I wasn't really sure if it was related and if so, what to even do. I did recently upgrade to Catalina, though I'm not sure if it was at that point that I started to have these crashes. Sorry I can't be of more help...

**Comment by MikhailArkhipov** [comment]
Since this appears telemetry-only functionality, I will just handle the exception.

**Comment by MikhailArkhipov** [comment]
0.5.9, currently in beta channel
