### ISSUE TITLE
NotImplementedException in PythonCollectionType.CreateSpecificType

### ISSUE THREAD

**Issue by xvzezi** [microsoft/python-language-server#1905]
## Environment data

- VS Code version: 1.42.0
- Extension version (available under the Extensions sidebar): 2020.2.62710
- OS and version: win 10 Home 1909, OS version: 18363.657
- Python version :3.7.6 
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...) None
- Relevant/affected Python packages and their versions: numpy 1.18.1, tensorflow 2.1.0
- Relevant/affected Python-related VS Code extensions and their versions: None, except for language extensions
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): None
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

when I type 
```numpy.zeros()```
it should come up with hints

## Actual behaviour

the auto-completion pop-up only displaying sub-packages names but member functions are lost
shown as followed img:
![image](https://user-images.githubusercontent.com/17743276/74324671-54356100-4dc2-11ea-879f-739c1c87a0eb.png)
there should be ```np.array``` in the list, and similarly, a bunch of functions are missed. same issue was found for tensorflow2

## Steps to reproduce:

1. install vscode
2. install tensorflow 2.1.0
3. install other requirements(CUDA etc.)
4. install vscode-python ext
5. open up a workspace and it shows up
Those are what i've done this afternoon. I am not sure if some parts are relevant 

## Logs
Nothing. But pylint, at the same time, is reporting ***the missing*** functions as missing members error
![image](https://user-images.githubusercontent.com/17743276/74325250-3f0d0200-4dc3-11ea-8b97-1864d2f69a31.png)

**Comment by jakebailey** [comment]
Please provide logs, per https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue.

Tensorflow 2.0 was designed in a way that makes it hard to statically analyzed, tracked on #818.

Pylint is a separate tool with its own import logic. It's concerning that even it cannot find your code, which makes it seem like there's something wrong with your installation.

**Comment by xvzezi** [comment]
[Python Language Server Output.txt](https://github.com/microsoft/python-language-server/files/4196257/Python.Language.Server.Output.txt)
[Python Output.txt](https://github.com/microsoft/python-language-server/files/4196259/Python.Output.txt)
Those are outputs when I input following codes in a new file:
```python
import numpy as np

a = np.zeros([1,4])

print(a)
```

**Comment by jakebailey** [comment]
This appears to be a bug, given the exception in the logs:

```
   at Microsoft.Python.Analysis.Types.Collections.PythonCollectionType.CreateSpecificType(IArgumentSet typeArguments) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Types\Collections\PythonCollectionType.cs:line 70
   at Microsoft.Python.Analysis.Analyzer.Evaluation.TypeAnnotationConverter.MakeGeneric(IPythonType baseType, IReadOnlyList`1 args) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Evaluation\TypeAnnotationConverter.cs:line 63
   at Microsoft.Python.Parsing.Ast.TypeAnnotation.Walker.MakeGenericOp.Apply[T](TypeAnnotationConverter`1 converter, Stack`1 stack) in E:\A\_work\3\s\src\Parsing\Impl\Ast\TypeAnnotation.cs:line 276
   at Microsoft.Python.Parsing.Ast.TypeAnnotation.Walker.GetResult[T](TypeAnnotationConverter`1 converter) in E:\A\_work\3\s\src\Parsing\Impl\Ast\TypeAnnotation.cs:line 68
   at Microsoft.Python.Parsing.Ast.TypeAnnotation.GetValue[T](TypeAnnotationConverter`1 converter) in E:\A\_work\3\s\src\Parsing\Impl\Ast\TypeAnnotation.cs:line 47
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.GetTypeFromAnnotation(Expression expr, LookupOptions options) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.Annotations.cs:line 23
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.TryAddBase(List`1 bases, Arg arg) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 151
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.ProcessBases() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 117
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.EvaluateClass() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 55
   at Microsoft.Python.Analysis.Analyzer.Symbols.ClassEvaluator.Evaluate() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ClassEvaluator.cs:line 37
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.Evaluate(MemberEvaluator e) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 100
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.Evaluate(ScopeStatement target) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 90
   at Microsoft.Python.Analysis.Analyzer.ModuleWalker.Walk(ClassDefinition node) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\ModuleWalker.cs:line 192
   at Microsoft.Python.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\ClassDefinition.cs:line 138
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 40
   at Microsoft.Python.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\PythonAst.cs:line 86
   at Microsoft.Python.Analysis.Analyzer.Handlers.LoopImportedVariableHandler.WalkModule(IPythonModule module, PythonAst ast) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\LoopImportedVariableHandler.cs:line 117
   at Microsoft.Python.Analysis.Analyzer.Handlers.LoopImportedVariableHandler.EnsureModule(IPythonModule& module) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\LoopImportedVariableHandler.cs:line 104
   at Microsoft.Python.Analysis.Analyzer.Handlers.LoopImportedVariableHandler.EnsureModule(PythonVariableModule& variableModule) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\LoopImportedVariableHandler.cs:line 94
   at Microsoft.Python.Analysis.Analyzer.Handlers.LoopImportedVariableHandler.Microsoft.Python.Analysis.Analyzer.Handlers.IImportedVariableHandler.EnsureModule(PythonVariableModule& module)
   at Microsoft.Python.Analysis.Analyzer.Handlers.ImportHandler.AssignVariables(FromImportStatement node, IImportSearchResult imports, PythonVariableModule variableModule) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\FromImportHandler.cs:line 60
   at Microsoft.Python.Analysis.Analyzer.Handlers.ImportHandler.HandleFromImport(FromImportStatement node) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\FromImportHandler.cs:line 45
   at Microsoft.Python.Analysis.Analyzer.AnalysisWalker.Walk(FromImportStatement node) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\AnalysisWalker.cs:line 81
   at Microsoft.Python.Parsing.Ast.FromImportStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\FromImportStatement.cs:line 58
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 40
   at Microsoft.Python.Parsing.Ast.IfStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\IfStatement.cs:line 51
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 40
   at Microsoft.Python.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\PythonAst.cs:line 86
   at Microsoft.Python.Analysis.Analyzer.Handlers.LoopImportedVariableHandler.WalkModule(IPythonModule module, PythonAst ast) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Handlers\LoopImportedVariableHandler.cs:line 117
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeLoop(IDependencyChainLoopNode`1 loopNode, Stopwatch stopWatch) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 392
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode node, Stopwatch stopWatch) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 272
```

**Comment by xvzezi** [comment]
And it seems that my PC's disk partition E is a system/OS reserved partition with nothing inside

**Comment by MikhailArkhipov** [comment]
0.5.47
