### ISSUE TITLE
Exception `stack empty` in document hover handler

### ISSUE THREAD

**Issue by yxiao-wish** [microsoft/python-language-server#1910]
##  Environment data

- VS Code version: 1.42.1
- Extension version (available under the Extensions sidebar): 2020.2.63072
- OS and version: 2020.2.63072
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.17
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Relevant/affected Python-related VS Code extensions and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

The language server works normally.

## Actual behaviour

The language server outputs this and gets stuck
```
[Info  - 10:51:13 a.m.] Analysis cache path: /home/xxxxxxx/snap/code/common/.cache/Microsoft/Python Language Server
[Info  - 10:51:13 a.m.] Microsoft Python Language Server version 0.5.30.0
[Info  - 10:51:13 a.m.] Workspace root:  xxxxxxxxxxxxxxxxxxxx
[Info  - 10:51:13 a.m.] GetCurrentSearchPaths /usr/bin/python 
[Info  - 10:51:13 a.m.] Interpreter search paths:
[Info  - 10:51:13 a.m.]     /usr/lib/python2.7
[Info  - 10:51:13 a.m.]     /usr/lib/python2.7/plat-x86_64-linux-gnu
[Info  - 10:51:13 a.m.]     /usr/lib/python2.7/lib-tk
[Info  - 10:51:13 a.m.]     /usr/lib/python2.7/lib-dynload
[Info  - 10:51:13 a.m.]     /hom
[Info  - 10:51:13 a.m.]     /home/yxiao/.local/lib/python2.7/site-packages
[Info  - 10:51:13 a.m.]     /usr/local/lib/python2.7/dist-packages
[Info  - 10:51:13 a.m.]     /usr/lib/python2.7/dist-packages
[Info  - 10:51:13 a.m.] User search paths:
[Info  - 10:51:13 a.m.]     /${workspaceRoot}/venv/lib/python2.7/site-packages
[Info  - 10:51:15 a.m.] Initializing for /usr/bin/python
[Info  - 10:51:15 a.m.] Analysis caching mode: None.
[Error - 11:55:31 a.m.] Request textDocument/hover failed.
  Message: Stack empty.
  Code: -32000 
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.ScopeTracker.Dispose() in E:\A\_work\8\s\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.Scopes.cs:line 198
   at Microsoft.Python.LanguageServer.Sources.HoverSource.GetHover(IDocumentAnalysis analysis, SourceLocation location) in E:\A\_work\8\s\src\LanguageServer\Impl\Sources\HoverSource.cs:line 147
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\Implementation\Server.Editor.cs:line 74
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\LanguageServer.cs:line 176
[Error - 10:39:53 a.m.] Request textDocument/hover failed.
  Message: Stack empty.
  Code: -32000 
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.ScopeTracker.Dispose() in E:\A\_work\8\s\src\Analysis\Ast\Impl\Analyzer\Evaluation\ExpressionEval.Scopes.cs:line 198
   at Microsoft.Python.LanguageServer.Sources.HoverSource.GetHover(IDocumentAnalysis analysis, SourceLocation location) in E:\A\_work\8\s\src\LanguageServer\Impl\Sources\HoverSource.cs:line 147
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\Implementation\Server.Editor.cs:line 74
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\LanguageServer.cs:line 176
```

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. The repo is very large and the problem shows up randomly.
2. After it gets stuck, "Microsoft Python Language Server" uses 0% CPU and TONS of RAM (33GB over 64GB)
3. I do not have Intellicode installed.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - control'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'WebHostNotebook - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> /usr/bin/python -c "import sys;print(sys.executable)"
> conda info --json
Starting Microsoft Python language server.
> /usr/bin/python -c "import jupyter"
> /usr/bin/python -c "import jupyter"
> /usr/bin/python -c "import notebook"
> /usr/bin/python -c "import notebook"
> conda --version
> /usr/bin/python -m autopep8 --diff --line-range 435 435 ~/xxxxx/xxxxxx.py
cwd: ~/xxxxxx
> /usr/bin/python -m autopep8 --diff --line-range 435 435 ~/xxxxx/xxxxxx.py
cwd: ~/xxxxxx
```

**Comment by Aya-Yang** [comment]
I have the same problem, and I use macOS 10.15.3, when the repo is large, PLS uses massive memory, leads to memory leak

**Comment by 1470391328** [comment]
This problem is an old one. In fact, the previous version also has this problem
