### ISSUE TITLE
"Cannot get required symbol ECDSA_sign from libssl" with remote connection to CentOS 7.7 on VS Code

### ISSUE THREAD

**Issue by dotbugfix** [microsoft/python-language-server#1919]
I'm running VS Code 1.41.1 on Windows and am connecting to a remote host (CentOS 7.7) to open a folder with Python files.

The VS Code GUI shows me this notification: "The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted."

The output panel for 'Python Language Server' has this info:

```
[Info  - 6:36:08 AM] Analysis cache path: /home/omkar/.cache/Microsoft/Python Language Server
[Info  - 6:36:08 AM] Microsoft Python Language Server version 0.5.30.0
[Info  - 6:36:08 AM] Workspace root: /workspace/li_11/automation/python
[Info  - 6:36:08 AM] GetCurrentSearchPaths /usr/bin/python3 
[Info  - 6:36:08 AM] Interpreter search paths:
[Info  - 6:36:08 AM]     /usr/lib64/python3.6
[Info  - 6:36:08 AM]     /usr/lib64/python3.6/lib-dynload
[Info  - 6:36:08 AM]     /usr/lib64/python3.6/site-packages
[Info  - 6:36:08 AM]     /usr/lib/python3.6/site-packages
[Info  - 6:36:08 AM] User search paths:
Cannot get required symbol ECDSA_sign from libssl
[Info  - 6:36:09 AM] Connection to server got closed. Server will restart.
[Error - 6:36:09 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:145817)
	at Object.dispose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:240077)
	at I.handleConnectionClosed (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:240251)
	at I.handleConnectionClosed (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:261561)
	at t (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:238454)
	at r.invoke (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350021)
	at i.fire (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350751)
	at V (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:137973)
	at r.invoke (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350021)
	at i.fire (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350751)
	at t.StreamMessageWriter.fireClose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:422101)
	at Socket.<anonymous> (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:422468)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 6:36:09 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:145817)
	at Object.dispose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:240077)
	at I.handleConnectionClosed (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:240251)
	at I.handleConnectionClosed (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:261561)
	at t (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:238454)
	at r.invoke (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350021)
	at i.fire (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350751)
	at V (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:137973)
	at r.invoke (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350021)
	at i.fire (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:350751)
	at t.StreamMessageWriter.fireClose (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:422101)
	at Socket.<anonymous> (/home/omkar/.vscode-server/extensions/ms-python.python-2020.2.64397/out/client/extension.js:1:422468)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
```

The CentOS version is:
```
$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

The OpenSSL version installed on the CentOS system is:
```
$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

Both `libssl.so` and `libcrypto.so` have the `ECDSA_sign` symbol that its looking for:
```
$ objdump -T /lib64/libcrypto.so | grep ECDSA_sign
000000000010fe90 g    DF .text  0000000000000085  OPENSSL_1.0.1_EC ECDSA_sign_ex
000000000010ff40 g    DF .text  000000000000004d  OPENSSL_1.0.1_EC ECDSA_sign_setup
000000000010ff20 g    DF .text  000000000000001e  OPENSSL_1.0.1_EC ECDSA_sign

$ objdump -T /lib64/libssl.so | grep ECDSA_sign
0000000000000000      DF *UND*  0000000000000000  OPENSSL_1.0.1_EC ECDSA_sign
```

What am I missing?

**Comment by jakebailey** [comment]
If anything, this would be something upstream in dotnet or a packaging issue in CentOS; we don't explicitly load these libraries. The last time OpenSSL caused issues was when 1.1 was made the default in Ubuntu and we had to do a rebuild.

Are you using IntelliCode? If so, I would try disabling it to see if the issue goes away (they pull in some extra stuff when loaded, but it could still be something we use).

**Comment by dotbugfix** [comment]
The _IntelliCode_ extension was not installed on the remote target. I installed it and saw the same error with the Python Language Server. Then I uninstalled it on the remote target. Now the error is gone and the language server starts normally!

I'm not sure what exactly fixed the issue, but it's solved for now. I guess I will have to live without IntelliCode and keep relying on my human intelligence to write code; it has worked out well so far!

Thanks for giving me something to try, @jakebailey. You can close the issue, although I can help if you want to investigate the root cause; the issue can be readily reproduced on a fresh CentOS 7 install.

**Comment by jrjena136** [comment]
Hi there,
I am facing same issue while running below command .  I have installed dotnet-sdk-5.0 and aspnetcore-runtime-5.0
Same command is working fine on ubuntu OS

`/usr/bin/dotnet /path/to/PasteItCleaned.Plugin.Standalone.dll --server.urls http://0.0.0.0:5000`

below is my machine details
```
openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

cat /etc/*-release
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Oracle Linux Server release 7.9


rpm -qa | grep openssl
openssl-libs-1.0.2k-21.el7_9.x86_64
openssl-devel-1.0.2k-21.el7_9.x86_64
openssl-1.0.2k-21.el7_9.x86_64
```

**Comment by deepakbammancheri** [comment]
I too facing same issue when trying to configure self hosted runner with git actions
# Authentication

**Cannot get required symbol ECDSA_sign from libssl**
./config.sh: line 81: 17355 Aborted                 ./bin/Runner.Listener configure "$@"
[root@sc-lco-53 actions-runner]#

Please help
