### ISSUE TITLE
Request textDocument/documentSymbol failed.   Unable to find document file:///

### ISSUE THREAD

**Issue by masx200** [microsoft/python-language-server#1924]
## Environment data

- Language Server version: 0.5.30.0
- OS and version: Linux m-PC 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux

- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux

## Expected behaviour

The file name is quite normal, but still can't open?

## Actual behaviour
```
Unable to find document file:///home/m/Documents/bottletest/hello.py

```

## Logs

```
[Error - 下午4:27:58] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:27:58] Request textDocument/documentSymbol failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.Server.HierarchicalDocumentSymbol(DocumentSymbolParams params, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\Implementation\Server.Symbols.cs:line 37
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DocumentSymbol(JToken token, CancellationToken cancellationToken) in E:\A\_work\8\s\src\LanguageServer\Impl\LanguageServer.cs:line 226
[Error - 下午4:27:58] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:02] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:02] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:03] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:03] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:04] Unable to find document file:///home/m/Documents/bottletest/hello.py
[Error - 下午4:28:05] Unable to find document file:///home/m/Documents/bottletest/hello.py

```

## Code Snippet / Additional lnformation

```python
from bottle import route, run, static_file, template
```

**Comment by MikhailArkhipov** [comment]
```
Unable to find document file:///home/m/Documents/bottletest/hello.py
```
Means there is no document in the document table and hence no analysis. By any chance, does it work if project is some other location?
