### ISSUE TITLE
"The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by FeryET** [microsoft/python-language-server#1992]
## Environment data

- Language Server version: 0.5.45.0
- OS and version: Ubuntu 19.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4, conda 4.8.3

## Expected behaviour

Not crashing probably.

## Actual behaviour

It crashes and keeps in the `analyzing in background` mode. 

## Logs

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Python.Analysis.Caching.TypeNames.GetPersistentQualifiedName(IMember m, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\TypeNames.cs:line 46
   at Microsoft.Python.Analysis.Caching.Models.FunctionModel.FromOverload(IPythonFunctionOverload o, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\Models\FunctionModel.cs:line 37
   at Microsoft.Python.Analysis.Caching.Models.FunctionModel.<>c__DisplayClass5_0.<.ctor>b__0(IPythonFunctionOverload s) in E:\A\_work\1\s\src\Caching\Impl\Models\FunctionModel.cs:line 33
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Microsoft.Python.Analysis.Caching.Models.FunctionModel..ctor(IPythonFunctionType func, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\Models\FunctionModel.cs:line 33
   at Microsoft.Python.Analysis.Caching.Models.CallableModel..ctor(IPythonType callable, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\Models\CallableModel.cs:line 54
   at Microsoft.Python.Analysis.Caching.Models.FunctionModel..ctor(IPythonFunctionType func, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\Models\FunctionModel.cs:line 32
   at Microsoft.Python.Analysis.Caching.Models.ModuleModel.GetFunctionModel(IDocumentAnalysis analysis, IVariable v, IPythonFunctionType f, IServiceContainer services) in E:\A\_work\1\s\src\Caching\Impl\Models\ModuleModel.cs:line 146
   at Microsoft.Python.Analysis.Caching.Models.ModuleModel.FromAnalysis(IDocumentAnalysis analysis, IServiceContainer services, AnalysisCachingLevel options) in E:\A\_work\1\s\src\Caching\Impl\Models\ModuleModel.cs:line 94
   at Microsoft.Python.Analysis.Caching.ModuleDatabase.<>c__DisplayClass20_0.<StoreModuleAnalysisAsync>b__0() in E:\A\_work\1\s\src\Caching\Impl\ModuleDatabase.cs:line 106
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Caching.ModuleDatabase.StoreModuleAnalysisAsync(IDocumentAnalysis analysis, Boolean immediate, CancellationToken cancellationToken) in E:\A\_work\1\s\src\Caching\Impl\ModuleDatabase.cs:line 106
   at Microsoft.Python.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__4_0(Object s) in E:\A\_work\1\s\src\Core\Impl\Extensions\TaskExtensions.cs:line 89
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

## Code Snippet / Additional lnformation

This is the code that it crashes into:

```
import requests 
import pandas as pd
print("hello word")
```

**Comment by MikhailArkhipov** [comment]
What's the caching level setting? Thanks

**Comment by FeryET** [comment]
@MikhailArkhipov The caching level is set at `Library` level. Also there are other flags:

```
    "python.analysis.cachingLevel": "Library",
    "python.analysis.memory.keepLibraryAst": false,
    "python.analysis.memory.keepLibraryLocalVariables": false,
```

**Comment by jakebailey** [comment]
Any caching level other than None is unsupported; the feature isn't complete. Disable caching and the crashes will go away.

Perhaps we should force disable this feature; there are a number of similar issues. #1918, #1895

**Comment by MikhailArkhipov** [comment]
It is in experimental stage so bugs are expected. Part of it is to collect information on usage and issues.
