### ISSUE TITLE
Couldn't start client Python Tools

### ISSUE THREAD

**Issue by GuillaumeDesforges** [microsoft/python-language-server#2033]
## Environment data

- VS Code version: 1.41.0
- Extension version (available under the Extensions sidebar): 2020.2.64397
- OS and version: NixOS 19.09 (unstable channel)
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): nix-shell, so N/A
- Relevant/affected Python packages and their versions: N/A
- Relevant/affected Python-related VS Code extensions and their versions: vscode-python
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Python Tools should start without error.

## Actual behaviour

Got

> Couldn't start client Python Tools

when using the Microsoft Language Server.

## Steps to reproduce:

I use VS Code with Remote Development to connect to my server which is on NixOS.
I use Nix Environment Selector to select my environment as described by my `shell.nix` file.
Opening a Python interactive development session or Jupyter Notebook will raise the error.
Note that I can run the cells properly.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - control'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'WebHostNotebook - control'
> conda --version
> conda info --json
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python -c "import sys;print(sys.executable)"
Starting Microsoft Python language server.
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -c "import jupyter"
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -c "import jupyter"
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -c "import notebook"
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -c "import notebook"
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m jupyter kernelspec --version
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m jupyter kernelspec --version
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 -m datascience.daemon --daemon-module=datascience.jupyter_daemon -v
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) -m jupyter notebook --no-browser --notebook-dir=/run/user/1000/8aa98e9f-134b-466f-86ed-06034e5221aa --config=/run/user/1000/8aa98e9f-134b-466f-86ed-06034e5221aa/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) -m jupyter kernelspec list --json
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) -m jupyter kernelspec list --json
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getJupyterKernels.py
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getJupyterKernels.py
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getServerInfo.py
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getServerInfo.py
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getServerInfo.py
> /nix/store/aqvgac7j316p93mcn0mcd51ni8vk0r5y-python3-3.7.6-env/bin/python3.7 (daemon) ~/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/datascience/getServerInfo.py
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Couldn't start client Python Tools
onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:196   ERR spawn /home/arsleust/.vscode-server/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer ENOENT: Error: spawn /home/arsleust/.vscode-server/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30/Microsoft.Python.LanguageServer ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Investigation

Turns out I can't start the Microsoft Language server :

```
~/.vscode-server/extensions/ms-python.python-2020.2.64397/languageServer.0.5.30 $ ./Microsoft.Python.LanguageServer 
-bash: ./Microsoft.Python.LanguageServer: No such file or directory
```

even though the file is clearly there (I can see it with `ls`).

There are a lot of .dll beside it in this folder, **did the extension download the wrong executable** ?

I use jedi for now as it seems to be working fine, but I'd rather use the MS Python LS.

**Comment by MikhailArkhipov** [comment]
Not all flavor of Linux are supported out of the box. There are no current plans to support more distros outside of generic .NET Core 3.1 Linux x64 support. You can try and install complete .NET 3.1 runtime from https://dotnet.microsoft.com/download/dotnet-core/3.1 for your platform, if you wish, but results are not 100% guaranteed - ex. .NET Core 3.1 is available for ARM but we do not build LS for ARM.

**Comment by jakebailey** [comment]
This was specifically a NixOS problem, not ARM. I had Karthik move it since it's not an extension bug.

**Comment by jakebailey** [comment]
Oops, didn't mean to reopen; I agree we're sort of stuck to what .NET allows us to do for now.
