### ISSUE TITLE
Type hints (autocomplete) on nested classes

### ISSUE THREAD

**Issue by schperplata** [microsoft/python-language-server#2053]
Issue Type: <b>Bug</b>

After update **2020.4.76186**, editor autocomplete doesn't work on nested classes although type hints are available.
Example:
```python
from typing import List

class MyDataClass:
    def __init__(self):
        self.foo: str = None
        self.bar: int = None

class Container():
    def __init__(self):
        self.myData: List[MyDataClass] = []

cont = Container()
cont.myData[0].
```
would show (with 2020.4.76186 and before):
![image](https://user-images.githubusercontent.com/8736111/82907307-bcb9df80-9f66-11ea-9912-af21bf413534.png)

...while versions afterward doesn't display any relevant recommendations (even this pop-up was forced by ctrl+space):
![image](https://user-images.githubusercontent.com/8736111/82907695-394cbe00-9f67-11ea-9515-d9f11cb6d4aa.png)

Extension version: 2020.4.76186
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by schperplata** [comment]
Any progress here? Newest version still fails to do autocomplete properly...
This is kind of a blocker - makes a great editor practically useless.

**Comment by kivo360** [comment]
This is basically the same problem I'm having. I just switched back to Jedi.

**Comment by schperplata** [comment]
I am using Jedi (and did when I reported this bug).

**Comment by schperplata** [comment]
Works on the latest ([v2020.6.88468](https://github.com/microsoft/vscode-python/tree/2020.6.88468)) version.

**Comment by schperplata** [comment]
Wrong. 
Works on nested classes, but not on Dict/List of custom classes.

**Comment by schperplata** [comment]
Additional findings: 
1. By selecting Jedi as engine, autocomplete doesn't work on compound objects of user type (lists/dictionaries of user defined classes). Beside that, Jedi seems quite stable.
2. By using Microsoft Language Server, autocomplete on such nested classes DOES work. However, it is extremely unstable and it does not deserve "works" tag: it is constantly re-analyzing files and often crashes in a way that no autocomplete/go to definition/recommendation works. VSC reload is necessary and sometimes it does the trick and sometimes it doesn't. When this happens, this can be found in _Log (window)_ tab:
```
[2020-06-18 16:12:38.402] [renderer1] [error] Language client is not ready yet: Error: Language client is not ready yet
	at k.sendRequest (c:\Users\domenj.ISYSTEM\.vscode\extensions\ms-python.python-2020.6.88468\out\client\extension.js:1:272551)
	at t.LanguageServerSymbolProvider.provideDocumentSymbols (c:\Users\domenj.ISYSTEM\.vscode\extensions\ms-python.python-2020.6.88468\out\client\extension.js:1:606148)
	at t.TestFileCodeLensProvider.getCodeLenses (c:\Users\domenj.ISYSTEM\.vscode\extensions\ms-python.python-2020.6.88468\out\client\extension.js:48:946387)
	at t.TestFileCodeLensProvider.provideCodeLenses (c:\Users\domenj.ISYSTEM\.vscode\extensions\ms-python.python-2020.6.88468\out\client\extension.js:48:945485)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:601
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:136
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:108)
	at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:572)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:696:947
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:695:632)
	at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:696:925)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:1013)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:705)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:293)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:802:156)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:416
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:649
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:243:629)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:824
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:737)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:89
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

A bit about my environment, since it probably isn't the most basic one:
My project is built from a sources on a few locations. Each of  this locations has it's own workspace and settings. My project add this locations to workspace via .env file and by standard "Add folder to workspace" action. While Jedi has no problem with linking to sources on other location (for example, go to definition in other source folder), MSL often fails and crashes until reload.

Let me know if I can do anything else to speed up the fix. This is really a blocker, makes VSC quite useless for serious py projects.

**Comment by schperplata** [comment]
@karthiknadig Ping! :) Any news here?

**Comment by jakebailey** [comment]
Karthik is not on the language server team and wouldn't be involve in fixing this.

You should try Pylance, our new language server with full typing support. https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/

**Comment by schperplata** [comment]
Switching to Pylance indeed solve this specific problem, however, other critical stuff is not working there, but works in old language server, so still no proper solution. Will report bug in pylance repo.
