### ISSUE TITLE
Getting error while running language server[standalone]

### ISSUE THREAD

**Issue by itthought** [microsoft/python-language-server#2127]
I am getting below error while my monaco client connected to language server

```
 Process terminated. Assertion failed.
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidOpenTextDocument(JToken token, CancellationToken cancellationToken) in /home/ubuntu/microsoft/python-language-server/src/LanguageServer/Impl/LanguageServer.cs:line 123
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Environment:
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1025-aws x86_64)

**Comment by arpitjain258** [comment]
Is this resolved?

**Comment by zyokia** [comment]
me too. any ideas

**Comment by maddy-nit** [comment]
mee too. any solution

**Comment by judej** [comment]
Thank you for the report. This project is no longer active. If you are using the Python language server in VSCode, the language server you are using is Pylance and please the http://github.com/microsoft/pylance-release to report issues. 

If you are using Visual Studio, then, please use http://github.com/microsoft/PTVS to report issues.

thank you
