### ISSUE TITLE
Exception `Start and End must be well ordered`

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#23]
https://github.com/Microsoft/vscode-python/issues/2221

```python
a = [1, "str", 3]
a[0]. #<- exception here
```

![image](https://user-images.githubusercontent.com/12820357/44934393-7d267b00-ad21-11e8-8b0d-6472fa72b098.png)

**Comment by qubitron** [comment]
I get this issue in django app from here: https://github.com/Microsoft/python-sample-vs-learning-django

It's intermittent though, here's DjangoPolls/app/models.py:
![completions](https://user-images.githubusercontent.com/17804393/45580355-12a72c00-b845-11e8-8f5e-7415de1c5ecb.gif)

**Comment by MikhailArkhipov** [comment]
Can't repro :-(

**Comment by MikhailArkhipov** [comment]
Will reactivate if it happens again

**Comment by qubitron** [comment]
I am seeing this with latest version
```
[Error - 9:28:39 AM] Request textDocument/completion failed.
  Message: Start and End must be well ordered
  Code: -32000 
[object Object]
```

When typing `models.` on line 5 of:
https://github.com/Microsoft/python-sample-vscode-django-tutorial/blob/master/hello/models.py

**Comment by qubitron** [comment]
Call stack:
```
[Error - 12:02:22 PM] System.ArgumentException: Start and End must be well ordered
   at Microsoft.PythonTools.SourceSpan.ValidateLocations(SourceLocation start, SourceLocation end) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Infrastructure\SourceSpan.cs:line 51
   at Microsoft.PythonTools.SourceSpan..ctor(SourceLocation start, SourceLocation end) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Infrastructure\SourceSpan.cs:line 36
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Implementation\Server.Completion.cs:line 80
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.<>c__DisplayClass39_0.<<Completion>b__0>d.MoveNext() in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\LanguageServer.cs:line 289
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.LogOnException[TResult](Func`1 func) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\LanguageServer.cs:line 476
[Error - 12:02:22 PM] Request textDocument/completion failed.
  Message: Start and End must be well ordered
  Code: -32000 
```

**Comment by jakebailey** [comment]
I can reproduce this. Minimal example:

```python
import sys

sys version
```

Type a `.` after `sys`. `CompletionAnalysis.Node` isn't `sys` like it should be, but is instead `version`. This makes `span.End > trigger`, and then it tries to make the result have a span of `new SourceSpan(span.Start, trigger)`, except that the trigger character is before the node that the completion analysis thinks it needs to process.
