### ISSUE TITLE
Backtrace.

### ISSUE THREAD

**Issue by mingwandroid** [Microsoft/python-language-server#318]
I ran into this just now on macOS using Anaconda Distribution's latest Python 3.7.1 build:

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.48.0
Initializing for /opt/conda/bin/python
[Error - 1:02:02 PM] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.BuiltinFunctionOverloadResult.get_Documentation()
   at Microsoft.PythonTools.Analysis.OverloadResultComparer.Equals(OverloadResult x, OverloadResult y)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.HashSet`1.Contains(T item)
   at System.Collections.Generic.HashSet`1.ContainsAllElements(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1.SetEquals(IEnumerable`1 other)
   at Microsoft.PythonTools.Analysis.Values.BuiltinFunctionInfo.Equals(Object obj)
   at Microsoft.PythonTools.Analysis.AnalysisValue.Microsoft.PythonTools.Analysis.IAnalysisSet.Add(AnalysisValue item, Boolean& wasChanged, Boolean canMutate)
   at Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo.AddType(AnalysisValue ns)
   at Microsoft.PythonTools.Analysis.TypedDef`1.AddTypes(IVersioned projectEntry, IAnalysisSet newTypes, Boolean enqueue, IProjectEntry declaringScope)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.AssignImportedModuleOrMember(String name, IAnalysisSet value, Boolean addRef, Node node, NameExpression nameReference)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.FinishImportModuleOrMember(ModuleReference module, IReadOnlyList`1 attribute, String name, Boolean addRef, Node node, NameExpression nameReference)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(FromImportStatement node)
   at Microsoft.PythonTools.Parsing.Ast.FromImportStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(IfStatement node)
   at Microsoft.PythonTools.Parsing.Ast.IfStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.AnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.HandleAnalyzable(IAnalyzable item, AnalysisPriority priority, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.ConsumerLoop()
```

**Comment by jakebailey** [comment]
This is #286. Given that 0.1.48 is after that issue was closed, it looks like it's not completely fixed. I'll mark this as a duplicate and reopen the original issue.

**Comment by MikhailArkhipov** [comment]
Thread race condition. `BuiltinFunctionOverloadResult` does
```cs
                if (_docTask != null) {
                    _docTask.Wait(200);
```

while task body is setting `docTask` to null. So between `if` and `Wait` `docTask` can become null.
