### ISSUE TITLE
Debug.Fail "unsupported constant type" in GetTypeFromObject when analyzing Django codebase

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#360]
Open up the django repo with a few files open and attach the debugger. Eventually, the debugger breaks in `PythonAnalyzer.GetAnalysisValueFromObjects`, hitting the `Debug.Fail`. Looking at the `value` being inspected, it's a `AstNestedPythonModuleMember` with the name `walk` coming from the module `email.iterators`, likely `Message.walk`: https://docs.python.org/3/library/email.compat32-message.html#email.message.Message.walk

```
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.GetTypeFromObject(Object value) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\PythonAnalyzer.cs:line 882
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.GetAnalysisValueFromObjects(Object attr) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\PythonAnalyzer.cs:line 787
   at Microsoft.PythonTools.Analysis.Values.BuiltinNamespace`1.GetTypeMember(Node node, AnalysisUnit unit, String name) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Values\BuiltinNamespace.cs:line 53
   at Microsoft.PythonTools.Analysis.Values.BuiltinInstanceInfo.GetTypeMember(Node node, AnalysisUnit unit, String name) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Values\BuiltinInstanceInfo.cs:line 62
   at Microsoft.PythonTools.Analysis.AnalysisValue.GetMember(Node node, AnalysisUnit unit, String name) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\AnalysisValue.cs:line 161
   at Microsoft.PythonTools.Analysis.AnalysisValueSetExtensions.GetMember(IAnalysisSet self, Node node, AnalysisUnit unit, String name) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\AnalysisValueSetExtensions.cs:line 41
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateMember(ExpressionEvaluator ee, Node node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 289
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 211
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 55
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 373
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 211
   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\ExpressionEvaluator.cs:line 55
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ForStatement node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\DDG.cs:line 228
   at Microsoft.PythonTools.Parsing.Ast.ForStatement.Walk(PythonWalker walker) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Parsing\Ast\ForStatement.cs:line 50
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\DDG.cs:line 665
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Parsing\Ast\SuiteStatement.cs:line 34
   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\Analyzer\FunctionAnalysisUnit.cs:line 88
   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\Users\jabaile\python-language-server\src\Analysis\Engine\Impl\AnalysisUnit.cs:line 139
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\Users\jabaile\python-la 	147.32s		
```

This happens many times, but you can mash "continue" until `walk` isn't being looked at anymore.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/546
