### ISSUE TITLE
Intellisense tooltip not using correct class method

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#392]
_From @u2berggeist on November 11, 2018 16:4_

## Environment data

- VS Code version: 1.28.2
- Extension version (available under the Extensions sidebar): 2018.10.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.6 
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: pandas 0.23.3

## Actual behavior

The Intellisense is currently mistaking a module function in it's tooltips with an unrelated class, specifically, `pandas.read_csv()`. As you can see below, the tool tip presented shows a docstring for a completely different class.

![pandas.read_csv()](https://user-images.githubusercontent.com/20801821/48315011-028a9f00-e59f-11e8-87f3-a45568315c82.png)

Then when you go to enter in the arguements, it provides irrelevant help:

![read_csv irrelevant tool tips](https://user-images.githubusercontent.com/20801821/48315109-24d0ec80-e5a0-11e8-83a9-5d82962ef5ba.png)

This mix-up then causes auto-completions later in the document to be irrelevant to the actual object (`pandas.read_csv()` outputs a DataFrame, which doesn't have the methods/functions `addendum` or `join`:

![irrelevant auto-completions](https://user-images.githubusercontent.com/20801821/48315032-47aed100-e59f-11e8-8104-1522898de3fe.png)

## Expected  behavior

Below is an example of what is expected, for example using `pandas.read_clipboard()`:

![pandas.read_clipboard()](https://user-images.githubusercontent.com/20801821/48314976-e2f37680-e59e-11e8-8eed-4d742b6e83d2.png)

![image](https://user-images.githubusercontent.com/20801821/48315143-885b1a00-e5a0-11e8-8ac4-2da7989a58f2.png)

Intellisense doesn't assign the variable `example` to any object type, so it doesn't create any relevant (or irrelevant) auto-completions.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.1.60.nupkg... complete.
Unpacking archive... done.
Microsoft Python Language Server version 0.1.60.0
Initializing for C:\tools\miniconda3\python.exe
##########Linting Output - pylint##########
************* Module point_sorting
7,0,error,E0001:invalid syntax (<unknown>, line 7)
##########Linting Output - pylint##########
************* Module point_sorting
7,7,error,E0602:Undefined variable 'raw_poin'

--------------------------------------------------------------------

Your code has been rated at 0.00/10 (previous run: 10.00/10, -10.00)



##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```

/C:/Users/[USERNAME]/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 
[Extension Host] Python Extension: All locators have completed locating, , Return Value: 
/C:/Users/[USERNAME]/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 
[Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
/C:/Users/[USERNAME]/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1409   ERR Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:90:883)
	at new e (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:305:76)
	at e.translate (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:306:725)
	at getPrecedingRange (C:\Users\[USERNAME]\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:43:39)
	at processEnter (C:\Users\[USERNAME]\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:31:17)
	at activateOnEnter (C:\Users\[USERNAME]\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:26:9)
	at context.subscriptions.push.vs.workspace.onDidChangeTextDocument.changeEvent (C:\Users\[USERNAME]\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:13:90)
	at e.fire (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptModelChanged (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:1008)
	at t._doInvokeHandler (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\[USERNAME]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

_Copied from original issue: Microsoft/vscode-python#3301_

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/52772386-35549100-2fed-11e9-861d-34d7a384e239.png)

![image](https://user-images.githubusercontent.com/12820357/52772425-49988e00-2fed-11e9-8ae2-b24842b80078.png)
