### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#452]
I often see this when hovering over library functions:
```
[Error - 12:56:56 PM] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)
[Error - 12:58:53 PM] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)
[Error - 12:58:53 PM] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)
[Error - 12:58:54 PM] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)
```

**Comment by MikhailArkhipov** [comment]
No longer applies with https://github.com/Microsoft/python-language-server/pull/546

**Comment by crazythinking** [comment]
I still have this error, and updated newest vscode 
版本: 1.31.1
提交: 1b8e8302e405050205e69b59abb3559592bb9e60
日期: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Comment by fenchu** [comment]
Is this in v1.31.1 from 2019-02-12 ?, still same error, please reopen.

**Comment by MikhailArkhipov** [comment]
Not yet. New analysis engine will be available in upcoming weeks, beta channel testing first. This is a major redesign, stay tuned. The change cannot be ported to the code base currently in the product.

**Comment by xnone** [comment]
The error is still not fixed for the latest version

**Comment by MikhailArkhipov** [comment]
We are not changing 0.1.x. 0.2.x is available on beta channel.
```json
"python.analysis.downloadChannel": "beta"
```
Ignore squiggle, the setting is not publicly exposed.

**Comment by Abbyyan** [comment]
The error is still not fixed for the latest version
版本： 1.40.1
OS： local(mac) remote (linux)
LSP: ccls
