### ISSUE TITLE
vsc spins forever and python-language-server eats all my memory

### ISSUE THREAD

**Issue by fenchu** [Microsoft/python-language-server#529]
vsc v1.30.2, windows10 
ms-python.python v2018.12.1
python 3.7.2 via -m venv

From time to time if I press ctrl+mouseclick to follow a code, like here it was just on json.dump.
(doesnt matter if it is basic modules or 
the animation below the folders goes indefinitely and Microsoft.Python.Language.Server.exe
start eating memory, until all my 32GB has been eaten up around 100MB minute.
CPU around 20-25% (But ist a quite fast I7-7900)

Below is a snapshot just after it started happening:
![vsc_pythonlanguageserve_neverstops](https://user-images.githubusercontent.com/11349883/50961862-2009b580-14c9-11e9-9a56-380e0ad80787.png)

I then just kill the language Server and then ctrl+click is snappy again.

This has occured for me since summer almost daily.

On linux with same code, vsc, same plugins and same python, but using pyenv instead of venv,
Never any problems.

**Comment by fenchu** [comment]
When I kill a growing process stacktrace looks like this (there is no stacktrace if I kill it while it is fine, just restarts)
```
Error: Connection got disposed.
	at Object.dispose (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:67379)
	at Object.dispose (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:155149)
	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:155324)
	at module.exports.t.LanguageClient.handleConnectionClosed (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:9:8677)
	at t (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:153626)
	at e.module.exports.e.invoke (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:188056)
	at e.module.exports.e.fire (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:188927)
	at H (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:59709)
	at e.module.exports.e.invoke (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:188056)
	at e.module.exports.e.fire (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:188927)
	at t.module.exports.e.fireClose (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:220061)
	at Socket.<anonymous> (C:\Users\morten.sensio\.vscode\extensions\ms-python.python-2018.12.1\out\client\extension.js:1:220484)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12)
```

**Comment by Moshikol** [comment]
same here vscode 1.30.2 python 3.6.4 windows 10.
![image](https://user-images.githubusercontent.com/19548879/50969120-01fe7e00-14e6-11e9-859a-766c6d0cd4fc.png)

**Comment by jakebailey** [comment]
Closing this, since #479/#495/#330 are closed. The new LS should not have this behavior.

**Comment by MikhailArkhipov** [comment]
0.2.16 is now available on beta channel. 
```json
"python.analysis.downloadChannel": "beta"
```
