### ISSUE TITLE
Python language server didn't work properly when editing '__init__.py'

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/python-language-server#572]
@CamberLoid commented on [Wed Jan 30 2019](https://github.com/Microsoft/vscode-python/issues/4226)

Issue Type: <b>Bug</b>

Python language server raised an exception and caused problems when handling this `import (modules),(),`  
After double-checking on my Windows, I am sure this is because of the extra comma in the import expression in `__init__.py` , 

Using Anaconda distribution. Have not tried to reproduce on other OS.

Environment data
---
- Version: 1.30.2 (user setup)  
- Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8  
- Date: 2019-01-07T22:54:13.295Z   
- Electron: 2.0.12  
- Chrome: 61.0.3163.100  
- Node.js: 8.9.3  
- V8: 6.1.534.41  
- OS: Windows_NT x64 10.0.18323

Actual behaviour
---
Cannot access origin libraries by Ctrl+(Modules), and the exceptions below.   
It acts like this  

![issue](https://user-images.githubusercontent.com/22998116/52004555-55228a00-2502-11e9-9af6-f73077e4b727.gif)

Expected behaviour
---
Access origin libraries by Ctrl+(Modules)  
and no Exceptions

Logs
---
```
[Error - 1:18:14 AM] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.ImportModule(ImportStatement& node, IModule& module, DottedName& moduleImportExpression, NameExpression& asNameExpression)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(ImportStatement node)
   at Microsoft.PythonTools.Parsing.Ast.ImportStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.AnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel)
   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.GroupAnalysis.Analyze(CancellationToken cancel)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.HandleAnalyzable(IAnalyzable item, AnalysisPriority priority, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Intellisense.AnalysisQueue.ConsumerLoop()
```

Extension version: 2019.1.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.18323

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (9.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

---

@d3r3kk commented on [Thu Jan 31 2019](https://github.com/Microsoft/vscode-python/issues/4226#issuecomment-459536232)

Verified, here's another gif that might help figure out the issue:

![4226_intellisense_exception_on_import_trailing_comma](https://user-images.githubusercontent.com/11466735/52090633-d01d8c00-2566-11e9-8ed7-dfb53e45fde6.gif)

This is using `Microsoft Python Language Server version 0.1.78.0`, Miniconda3 on Windows with Python 3.7.2

**Comment by d3r3kk** [comment]
## Output found in the `Output:Log(Window)`
```
[2019-01-31 14:43:51.417] [renderer1] [error] name must not be falsy: Error: name must not be falsy
	at Function.e.validate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:869)
	at new e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:807)
	at R (C:\Users\derek\.vscode\extensions\ms-python.python-2019.1.0\out\client\extension.js:83:93748)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (C:\Users\derek\.vscode\extensions\ms-python.python-2019.1.0\out\client\extension.js:83:97402)
	at module.exports.R.registerLanguageProvider.t.sendRequest.then.e (C:\Users\derek\.vscode\extensions\ms-python.python-2019.1.0\out\client\extension.js:1:142452)
	at <anonymous>
```

## Problems Window
![image](https://user-images.githubusercontent.com/11466735/52090838-5e920d80-2567-11e9-9b6b-bae8b1835f69.png)

**Comment by jakebailey** [comment]
Aha, so that's what that stack trace is.

The diagnostics not going away are likely due to the LS exiting and leaving them there.

**Comment by jakebailey** [comment]
For reference, this was likely a bug beforehand too, it's just that the latest release now will actually report the exception and exit rather than swallowing it and then silently refusing any future requests.

**Comment by MikhailArkhipov** [comment]
Verity with new LS.

**Comment by MikhailArkhipov** [comment]
Verified, there is a test for that in https://github.com/Microsoft/python-language-server/pull/602.
Fix is not in public release yet, it will be some time before it gets to public since we are in a major rework of the LS.
