### ISSUE TITLE
Switching language mode to Python on an unsaved file throws "Module path should be rooted"

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#598]
On the old LS in `release`:

```
Opening document untitled:Untitled-1
[Error - 10:48:38 AM] Request textDocument/completion failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Implementation\ProjectFiles.cs:line 53
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Implementation\ProjectFiles.cs:line 59
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\Implementation\Server.Completion.cs:line 34
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken) in C:\Users\jabaile\python-language-server\src\LanguageServer\Impl\LanguageServer.cs:line 301
```

The file gets opened, but doesn't seem to get added anywhere, nor analyzed. This may also be causing exceptions on file updates which I'm not sure are logged in the output panel.

To reproduce (same as #597):

1. Open a new file in VSC, do not save.
2. Use the command palette to change the language mode to Python.
3. Try to use the analysis (completion, hover, etc).

**Comment by MikhailArkhipov** [comment]
That was fixed with https://github.com/Microsoft/python-language-server/pull/837

**Comment by jakebailey** [comment]
Yup, this was the issue for the old LS (which is now defunct).
