### ISSUE TITLE
InvalidOperationException in PathResolverSnapshot.TryFindModule

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#599]
Seeing this stack trace happening pretty often in the RPC exceptions:

```
 at Microsoft.PythonTools.Analysis.DependencyResolution.PathResolverSnapshot.TryFindModule(String modulePath, Edge& lastEdge, StringSpan& unmatchedPathSpan)
 at Microsoft.PythonTools.Analysis.DependencyResolution.PathResolverSnapshot.AddModulePath(String& modulePath, String& fullModuleName)
 at Microsoft.PythonTools.Analysis.PythonAnalyzer.AddModule(String moduleName, String filePath, Uri documentUri, IAnalysisCookie cookie)
 at Microsoft.Python.LanguageServer.Implementation.Server.AddFileAsync(Uri documentUri, IAnalysisCookie cookie)
 at Microsoft.Python.LanguageServer.Implementation.Server.DidOpenTextDocument(DidOpenTextDocumentParams params, CancellationToken token)
 at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidOpenTextDocument(JToken token, CancellationToken cancellationToken)
```

Seems to be thrown whenever a module gets added that isn't rooted, but I haven't been able to actually reproduce it. It feels like it should be related to #598, but I don't get past that issue's trace.

@AlexanderSher 	I believe this would be carried over to the new LS, so would continue to impact things. Is there a better mechanism for handling this scenario rather than throwing an exception and bailing out?

**Comment by AlexanderSher** [comment]
It is a good question how we end up with the non-rooted path.

**Comment by MikhailArkhipov** [comment]
Merging into #597
