### ISSUE TITLE
BadSourceException being raised

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#65]
Microsoft/vscode-python#2501

```
Reloading modules...

Unhandled Exception: Microsoft.PythonTools.Parsing.BadSourceException: Exception of type 'Microsoft.PythonTools.Parsing.BadSourceException' was thrown.
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter.ImportModule(String name)
   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.GetModule()
   at Microsoft.PythonTools.Interpreter.Ast.AstNestedPythonModule.GetChildrenModules()
   at Microsoft.PythonTools.Analysis.ModuleTable.ReInit()
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.Interpreter_ModuleNamesChanged(Object sender, EventArgs e)
   at Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory.NotifyImportNamesChanged()
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.ReloadModulesAsync(CancellationToken token)
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.ReloadModulesQueueItem.Analyze(CancellationToken cancel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.ReloadModulesAsync(CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 3:42:56 PM] Connection to server got closed. Server will restart.
Initializing for /home/cllamach/.virtualenvs/panopta_env/bin/python
```

**Comment by MikhailArkhipov** [comment]
BadSourceException means file contains characters that are out of declared encoding. Such as characters over 0x7F in file that is considered ASCII.

```cs
defaultEncoding = version.Is2x() ? PythonAsciiEncoding.Instance : Encoding.UTF8
```
