### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Emit.ILGeneration

### ISSUE THREAD

**Issue by gramster** [Microsoft/python-language-server#675]
@kodalipraveen commented on [Wed Feb 27 2019](https://github.com/Microsoft/vscode-python/issues/4584)

Issue Type: <b>Bug</b>

The below Error keeps coming up in Output->Pyhton when working on python files.

[Error - 11:45:56 AM] System.TypeInitializationException: The type initializer for 'Microsoft.PythonTools.Analysis.Indexing.SymbolIndexWalker' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Emit.ILGeneration, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

   at System.Text.RegularExpressions.Regex.Compile(RegexCode code, RegexOptions roptions)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at Microsoft.PythonTools.Analysis.Indexing.SymbolIndexWalker..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Analysis.Indexing.SymbolIndexWalker.Walk(FunctionDefinition node)
   at Microsoft.PythonTools.Parsing.Ast.FunctionDefinition.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Indexing.SymbolIndexWalker.Walk(ClassDefinition node)
   at Microsoft.PythonTools.Parsing.Ast.ClassDefinition.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.PythonTools.Analysis.Indexing.SymbolIndex.UpdateParseTree(Uri uri, PythonAst ast)
   at Microsoft.Python.LanguageServer.Implementation.Server.UpdateSymbolIndex(Object sender, ParseCompleteEventArgs args)
   at Microsoft.Python.LanguageServer.Implementation.Server.OnDocumentChangeProcessingComplete(IDocument doc, VersionCookie vc, Boolean enqueueForAnalysis, AnalysisPriority priority, IDisposable disposeWhenEnqueued)

Extension version: 2019.2.5433
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by MikhailArkhipov** [comment]
Make sure you don't get many old frameworks installed, sometimes they got confused...
https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos

**Comment by jakebailey** [comment]
I'm going to close this, they were asked to delete the extension (which would delete the language server) to reset things but didn't respond. That'd be the first thing to try, if some assembly we have isn't found; maybe an extract issue.

Microsoft/vscode-python#4584
