### ISSUE TITLE
Intellisense does not work inside function body

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#760]
@programmer04 commented on [Thu Feb 21 2019](https://github.com/Microsoft/vscode-python/issues/4491)

## Environment data

- VS Code version: **1.31.1**
- Extension version: **2019.1.0**
- OS and version: **macOS 10.14.3**
- Python version: **3.7.2**
- Type of virtual environment used: **N/A**
- Relevant/affected Python packages and their versions: **N/A**

## Expected behaviour

Intellisense support in function body and after leaving it (now it sometimes does not work).

## Actual behaviour

Lack of Intellisense inside a function, only available when forced with `⌃Space`, after leaving function body also unavailable. 

![vs-code](https://user-images.githubusercontent.com/9593424/53202730-8edd4100-3627-11e9-8aed-c9894261b1a7.gif)

## Steps to reproduce:

Follow **Actual behaviour**

## Logs

```
ERR name must not be falsy: Error: name must not be falsy
	at Function.e.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:775)
	at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:713)
	at R (/Users/user/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:93748)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/user/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:83:97402)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/user/.vscode/extensions/ms-python.python-2019.1.0/out/client/extension.js:1:142452)
```

---

@programmer04 commented on [Thu Feb 28 2019](https://github.com/Microsoft/vscode-python/issues/4491#issuecomment-468177484)

On windows machine, I can observe the same behavior

---

@DonJayamanne commented on [Tue Mar 05 2019](https://github.com/Microsoft/vscode-python/issues/4491#issuecomment-469762415)

* Please could you test this with the latest version of the extension.
* If it occurs again, please upload the error logs (as you did earlier).
* Please could you open the `Python Output` panel and upload the contents of that as well (use the command `Python: Show Output` from the command palette)
Thanks

---

@programmer04 commented on [Tue Mar 05 2019](https://github.com/Microsoft/vscode-python/issues/4491#issuecomment-469848302)

I investigated this behavior with the new version of Python extension and the below description is probably more accurate.

## Environment data
VS Code version: **1.31.1**
Extension version: **2019.2.5433**
OS and version: **macOS 10.14.3**
Python version: **3.7.2**
Type of virtual environment used: **N/A**
Relevant/affected Python packages and their versions: **N/A**

## Expected behavior
Intellisense supports inside snippet provided code and after leaving it (now it often does not work).

## Actual behavior
I discover that this bug only occurs when I use code snippet. It does not matter which _if_, _def_, _while_, etc. After using it Intellisense stops working.

![vs-code-bug](https://user-images.githubusercontent.com/9593424/53835000-b23fae80-3f8c-11e9-8b71-9b9e2e45cc7c.gif)

## Steps to reproduce
Follow Actual behavior

## Logs
```
   ERR name must not be falsy: Error: name must not be falsy
	at Function.e.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:775)
	at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:713)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.2.5433/out/client/extension.js:83:94031)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/user/.vscode/extensions/ms-python.python-2019.2.5433/out/client/extension.js:83:97685)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/user/.vscode/extensions/ms-python.python-2019.2.5433/out/client/extension.js:1:155742)
log.ts:173   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/Users/user/.vscode/extensions/ms-python.python-2019.2.5433/out/client/extension.js:83:96829)
log.ts:173   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
	at asCompletionResult (/Users/user/.vscode/extensions/ms-python.python-2019.2.5433/out/client/extension.js:83:96829)
```

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.80.0
Initializing for /usr/local/opt/python/bin/python3.7
```

**Comment by MikhailArkhipov** [comment]
Is this on 0.2 with
```json
"python.analysis.downloadChannel": "beta"
```
?

**Comment by programmer04** [comment]
@MikhailArkhipov I have only `Microsoft Python Language Server version 0.1.80.0` available in the newest version of VS Code. It should update automatically, shouldn't it?

**Comment by jakebailey** [comment]
We have not pushed this to the stable channel quite yet (there are a few things left to do). The only way to get 0.2 is to set the download channel to `beta` or `daily` (or to build yourself).

**Comment by programmer04** [comment]
@jakebailey After the update, it stops working entirely. There is similar issue in extension **vscode-python** _#5010_.

**Comment by MikhailArkhipov** [comment]
Could you provide more detail on exactly stops working entirely?

**Comment by programmer04** [comment]
There are syntax highlighting and snippets, but autocompletion and checking syntax are not working. It's strange because it used to work.

**Comment by MikhailArkhipov** [comment]
Is extension active? What is in the Python output window?

**Comment by programmer04** [comment]
Extension is active, output:
```
Starting Microsoft Python language server.
[Info  - 10:34:28 AM] GetCurrentSearchPaths /usr/local/opt/python/bin/python3.7 
[Info  - 10:34:29 AM] Python search paths:
[Info  - 10:34:29 AM]     /private/var/folders/4f/228_vcj911s994kpp_0c7k_r0000gn/T/l0ubzxud.50x
[Info  - 10:34:29 AM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 10:34:29 AM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 10:34:29 AM]     /Users/jakubwarczarek/Library/Python/3.7/lib/python/site-packages
[Info  - 10:34:29 AM]     /usr/local/lib/python3.7/site-packages
[Info  - 10:34:29 AM] Configuration search paths:
[Info  - 10:34:29 AM]     /
[Info  - 10:34:29 AM]     /Users/jakubwarczarek/Library/Python/3.7/lib/python/site-packages
[Info  - 10:34:29 AM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
[Info  - 10:34:29 AM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 10:34:29 AM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 10:34:29 AM]     /usr/local/lib/python3.7/site-packages
[Info  - 10:34:29 AM]     /Users/jakubwarczarek/Library/Python/3.7/lib/python/site-packages/
[Info  - 10:34:29 AM]     /Users/jakubwarczarek/Library/Python/3.7/lib/python/site-packages/
[Info  - 10:34:29 AM]     /usr/local/opt/python/bin
```

**Comment by MikhailArkhipov** [comment]
Set `"python.analysis.logLevel": "Trace",` and let's see what is in the output. Do you mean that there is no completion whatsoever, not even keywords?

**Comment by programmer04** [comment]
Yes, there is no completion even for keywords. Trace output:
```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.38.nupkg... complete
Unpacking archive... done
[Info  - 8:58:08 PM] GetCurrentSearchPaths /usr/local/opt/python/bin/python3.7 
[Info  - 8:58:08 PM] Python search paths:
[Info  - 8:58:08 PM]     /private/var/folders/4f/228_vcj911s994kpp_0c7k_r0000gn/T/guj3grxt.seh
[Info  - 8:58:08 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 8:58:08 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 8:58:08 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages
[Info  - 8:58:08 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 8:58:08 PM] Configuration search paths:
[Info  - 8:58:08 PM]     /
[Info  - 8:58:08 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages
[Info  - 8:58:08 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
[Info  - 8:58:08 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 8:58:08 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 8:58:08 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 8:58:08 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages/
[Info  - 8:58:08 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages/
[Info  - 8:58:08 PM]     /usr/local/opt/python/bin
```

**Comment by MikhailArkhipov** [comment]
You may want to adjust your search paths. Root `/` probably should not be there.

**Comment by programmer04** [comment]
It's interesting when I open project like this:

`code ~/Documents/repositories/repos-python/test-lang-serv`

I got:
```
Starting Microsoft Python language server.
[Info  - 11:01:40 PM] GetCurrentSearchPaths /usr/local/opt/python/bin/python3.7 
[Info  - 11:01:40 PM] Python search paths:
[Info  - 11:01:40 PM]     /private/var/folders/4f/228_vcj911s994kpp_0c7k_r0000gn/T/cves5tc0.wjx
[Info  - 11:01:40 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 11:01:40 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 11:01:40 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages
[Info  - 11:01:40 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 11:01:40 PM] Configuration search paths:
[Info  - 11:01:40 PM]     /Users/macuser
[Info  - 11:01:40 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages
[Info  - 11:01:40 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
[Info  - 11:01:40 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7
[Info  - 11:01:40 PM]     /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
[Info  - 11:01:40 PM]     /usr/local/lib/python3.7/site-packages
[Info  - 11:01:40 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages/
[Info  - 11:01:40 PM]     /Users/macuser/Library/Python/3.7/lib/python/site-packages/
[Info  - 11:01:40 PM]     /usr/local/opt/python/bin
[Info  - 11:03:09 PM] Microsoft Python Language Server version 0.2.38.0
[Info  - 11:03:09 PM] Initializing for /usr/local/opt/python/bin/python3.7
Opening document file:///Users/macuser/Documents/repositories/repos-python/test-lang-serv/test.py
Opening document file:///Users/macuser/Documents/repositories/repos-python/test-lang-serv/x.py
Analysis of x(User) queued
Analysis version 2 of 1 entries has started.
Analysis of test(User) queued
Analysis of x(User) completed in 54.6606 ms.
Analysis version 2 of 1 entries has been completed in 54.871 ms.
Import:  mailbox /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mailbox.py 
Analysis version 3 of 2 entries has started.
Analysis of x(User) completed in 0.3051 ms.
...
```
So there is no root path in configuration search pass. But when I open with vscode icon from dock I got this previous log with root path.
I observed that in the presented above case everything started working after 1 minute and 29 seconds. Is it normal behavior?

**Comment by MikhailArkhipov** [comment]
Depends on the size of the project and imported libraries. The data comes in stages.

**Comment by MikhailArkhipov** [comment]
OK, closing this one per working functionality, performance improvements have separate issues open.
