### ISSUE TITLE
Server initialization failed.   Message: Value cannot be null.

### ISSUE THREAD

**Issue by qci-amos** [Microsoft/python-language-server#790]
## Environment data

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

```
    "python.analysis.downloadChannel": "beta",
```

- Extension version (available under the Extensions sidebar): 2019.2.5558
- Python version (& distribution if applicable, e.g. Anaconda): none selected

## Expected behaviour

no errors

## Actual behaviour

error message reported in output

## Steps to reproduce:

Don't know. All I did was restart vscode and open a python file.

## Logs

```
Starting Microsoft Python language server.
[Error - 9:59:33 AM] Server initialization failed.
  Message: Value cannot be null.
Parameter name: key
  Code: -32000 
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Python.Analysis.Documents.RunningDocumentTable.UnlockDocument(Uri uri)
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.ReloadAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.InitializeAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.LoadBuiltinTypesAsync(String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.CreateAsync(InterpreterConfiguration configuration, String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)
```

**Comment by qci-amos** [comment]
here's another I haven't noticed until now:

```
[Error - 2:05:41 PM] Server initialization failed.
  Message: Sequence contains no elements
  Code: -32000 
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Python.Core.IO.DirectoryInfoProxy.<EnumerateFileSystemInfos>b__13_0(FilePatternMatch filePatternMatch)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Microsoft.Python.LanguageServer.Indexing.IndexManager.StartAddRootDir()
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)
```

For this one, I do have a conda set, it's using Python 3.6.8.

**Comment by jakebailey** [comment]
Can you file a second bug for that issue? It's likely unrelated to the first.
