### ISSUE TITLE
Server initialization failed.   Message: Sequence contains no elements

### ISSUE THREAD

**Issue by qci-amos** [Microsoft/python-language-server#791]
splitting 2nd issue from #790 into here (same vscode, just it's a new bug) 

here's another I haven't noticed until now:

```
[Error - 2:05:41 PM] Server initialization failed.
  Message: Sequence contains no elements
  Code: -32000 
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Python.Core.IO.DirectoryInfoProxy.<EnumerateFileSystemInfos>b__13_0(FilePatternMatch filePatternMatch)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Microsoft.Python.LanguageServer.Indexing.IndexManager.StartAddRootDir()
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)
```

For this one, I do have a conda set, it's using Python 3.6.8.

**Comment by jakebailey** [comment]
@brianbok
