### ISSUE TITLE
Server initialization failed.   Message: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by qci-amos** [Microsoft/python-language-server#807]
downloaded new language server just now and I saw this exception. same vscode setup as #790 and #791  

```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-beta/Python-Language-Server-win-x64.0.2.28.nupkg... complete
Unpacking archive... done
[Info  - 8:03:15 AM] Python search paths:
[Info  - 8:03:15 AM] Configuration search paths:
[Info  - 8:03:15 AM]     .
[Error - 8:03:16 AM] Server initialization failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.Analysis.Modules.Resolution.ModuleResolutionBase.get_CurrentPathResolver()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.FindDependencies(IPythonModule module, PythonAst ast, Int32 bufferVersion)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.Invalidate(IPythonModule module, PythonAst ast, Int32 bufferVersion, Int32 analysisVersion, ImmutableArray`1& dependencies)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.EnqueueDocumentForAnalysis(IPythonModule module, PythonAst ast, Int32 bufferVersion, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Modules.PythonModule.Parse(CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Modules.PythonModule.GetAstAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Modules.PythonModule.LoadAndAnalyzeAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.LoadBuiltinTypesAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.LoadBuiltinTypesAsync(String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.CreateAsync(InterpreterConfiguration configuration, String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)
```

```
[2019-03-21 08:02:39.056] [renderer1] [info] no standard startup: panel is active
[2019-03-21 08:02:49.570] [renderer1] [info] no standard startup: not a new window
[2019-03-21 08:03:17.324] [renderer1] [error] Object reference not set to an instance of an object.: Error: Object reference not set to an instance of an object.
	at new t (C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\out\client\extension.js:83:51819)
	at C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\out\client\extension.js:1:89179
	at C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\out\client\extension.js:1:89473
	at Immediate.<anonymous> (C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\out\client\extension.js:1:89832)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
```

**Comment by qci-amos** [comment]
fyi, I switched it to a different workspace, and this time I got this:

```
Starting Microsoft Python language server.
C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\languageServer.0.2.28\scrape_module.py:997: InspectWarning: attribute __abstractmethods__ on <class 'type'> was in dir() but not getattr()
  warnings.warn("attribute " + name + " on " + repr(mod) + " was in dir() but not getattr()", InspectWarning)
[Info  - 8:47:54 AM] GetCurrentSearchPaths C:\Users\me\AppData\Local\conda\conda\envs\my_env\python.exe 
[Info  - 8:47:54 AM] Python search paths:
...
[Info  - 8:47:54 AM]     .
[Info  - 8:47:54 AM]     C:\Users\me\AppData\Local\conda\conda\envs\my_env
[Info  - 8:48:08 AM] Microsoft Python Language Server version 0.2.28.0
[Info  - 8:48:08 AM] Initializing for C:\Users\me\AppData\Local\conda\conda\envs\my_env\python.exe
C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\languageServer.0.2.28\scrape_module.py:597: InspectWarning: failed to tokenize tm_sec, tm_wday, tm_yday, tm_isdst)
  warnings.warn('failed to tokenize ' + expr, InspectWarning)
C:\Users\me\.vscode\extensions\ms-python.python-2019.2.5558\languageServer.0.2.28\scrape_module.py:597: InspectWarning: failed to tokenize tm_sec,tm_wday,tm_yday,tm_isdst)
  warnings.warn('failed to tokenize ' + expr, InspectWarning)
[Error - 8:49:16 AM] Extension provider C:\Users\me\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.4\dist\IntellicodeForPython.dll Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtensionProvider failed to load
```

not sure if this is a problem I care about or if it's related to the other exception

**Comment by MikhailArkhipov** [comment]
Some warning from compiler modules inspection are OK, we suppressed then recently. Intellicode is not yet compatible with LS 0.2 so output is not unusual.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/809. Most probably path to the Python.

**Comment by qci-amos** [comment]
> Some warning from compiler modules inspection are OK, we suppressed then recently. Intellicode is not yet compatible with LS 0.2 so output is not unusual.

Understood... the behavior I'm experiencing is the OUTPUT panel continually popping open (which signals something I should worry about and possibly report to you all) when it complains about intellicode failing to load, I'm guessing simply because that message is an `Error`? Not a big deal, but maybe just demote it to `Info` for now?

**Comment by jakebailey** [comment]
Have you selected an interpreter? No interpreter name is shown at startup, which to me says that the extension hasn't sent one, i.e. this is #809.

**Comment by qci-amos** [comment]
I went back to the workspace where this occurred and indeed, no interpreter was selected, and the error was reported.

**Comment by MikhailArkhipov** [comment]
Resolving then per #807, #809 and #810.
