### ISSUE TITLE
Repeated output message with Pandas

### ISSUE THREAD

**Issue by albireox** [Microsoft/python-language-server#817]
With the last version of the language server I get repeated messages like this in the output window

```
Traceback (most recent call last):
  File "/Users/albireo/.vscode-insiders/extensions/ms-python.python-2019.4.6033-alpha/languageServer.0.2.30/scrape_module.py", line 1489, in <module>
    state.initial_import(sys.argv[2])
  File "/Users/albireo/.vscode-insiders/extensions/ms-python.python-2019.4.6033-alpha/languageServer.0.2.30/scrape_module.py", line 872, in initial_import
    mod = __import__(self.module_name)
  File "/Users/albireo/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/albireo/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/compat/__init__.py", line 446, in <module>
    import typing
  File "/Users/albireo/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/Users/albireo/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

They don't seem to break anything as far as I can see.

**Comment by MikhailArkhipov** [comment]
@jakebailey - was it suppressed with https://github.com/Microsoft/python-language-server/pull/798 ?

**Comment by jakebailey** [comment]
Warnings from the warnings module are suppressed, not actual exceptions. The AttributeError would still show.

**Comment by MikhailArkhipov** [comment]
Should suppress them too IMO. They don't provide any value to the user.
