### ISSUE TITLE
Unable to find document file 

### ISSUE THREAD

**Issue by tmab2003** [Microsoft/python-language-server#838]
[Error - 3:21:06 PM] Unable to find document file:///c:/Users/username/git/.../.../.../08_011_HMI.py
[Error - 3:21:06 PM] Request textDocument/definition failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Sources.DefinitionSource.FindDefinition(IDocumentAnalysis analysis, SourceLocation location)
   at Microsoft.Python.LanguageServer.Implementation.Server.GotoDefinition(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GotoDefinition(JToken token, CancellationToken cancellationToken)

Using Microsoft Python Language Server version 0.2.34.0

**Comment by jakebailey** [comment]
This is #736, which we just merged a PR to fix. There's a build in progress with that change now.

**Comment by tmab2003** [comment]
Oh oops - thanks!
