### ISSUE TITLE
KeyNotFound exception in symbol index

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#852]
Seeing these two stack traces show up quite a bit:

```
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.Python.LanguageServer.Indexing.SymbolIndex.MarkAsPending(String path)
   at Microsoft.Python.LanguageServer.Indexing.IndexManager.AddPendingDoc(IDocument doc)
   at Microsoft.Python.LanguageServer.Implementation.Server.DidChangeTextDocument(DidChangeTextDocumentParams params)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidChangeTextDocument(JToken token, CancellationToken cancellationToken)
```

```
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.Python.LanguageServer.Indexing.SymbolIndex.MarkAsPending(String path)
   at Microsoft.Python.LanguageServer.Implementation.Server.DidChangeTextDocument(DidChangeTextDocumentParams params)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidChangeTextDocument(JToken token, CancellationToken cancellationToken)
```

**Comment by jakebailey** [comment]
This was not caused by untitled/bad file names, as far as I can tell, given it's continuing into the latest release.
