### ISSUE TITLE
Language server initialization failed:  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#934]
@rivasd commented on [Wed Apr 10 2019](https://github.com/Microsoft/vscode-python/issues/5195)

After upgrading to the latest Microsoft Python Language Server, if  fails to initialize but only when applying the current fix for #3840. I would really like to remove all the pesky unresolved import errors that starting appearing recently, but now the LS does not work. 

## Environment data

- VS Code version: 1.33.0
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: Win 10
- Python version : Anaconda Python 3.7.0
- Type of virtual environment used : conda 
- Relevant/affected Python packages and their versions: Microsoft Python Language Server

## Expected behaviour

The Microsoft Python Language Server starts normally when a Python editor is opened

## Actual behaviour

The server immediately crashes and does not initialize

## Steps to reproduce:
1. Tried @Spenhouet 's answer to #3840 and created a `.env` with the contents
```
PYTHONPATH=./MyPackage
```
and added
```
"python.envFile": "${workspaceFolder}/.env
```
to my `settings.json`

2. Restarted VSCode

3. Tried opening any Python source file in the editor

**Does not happen when omitting step 1, but then I have a bunch of unresolved import errors**

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
[Info  - 8:08:39 PM] GetCurrentSearchPaths E:\Users\Nini\Miniconda3\envs\mne\python.exe 
[Info  - 8:08:40 PM] Python search paths:
[Info  - 8:08:40 PM]    < multiple paths >
[Info  - 8:08:40 PM] Configuration search paths:
[Info  - 8:08:40 PM]     <multiple paths >
[Error - 8:08:40 PM] Server initialization failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.Analysis.Core.DependencyResolution.PathResolverSnapshot.AddModulePath(String& modulePath, Boolean& allowNonRooted, String& fullModuleName)
   at Microsoft.Python.Analysis.Modules.Resolution.ModuleResolutionBase.ReloadModulePaths(IEnumerable`1& rootPaths)
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.ReloadAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Modules.Resolution.MainModuleResolution.InitializeAsync(CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.LoadBuiltinTypesAsync(String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonInterpreter.CreateAsync(InterpreterConfiguration configuration, String root, IServiceManager sm, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
stack trace: Error: Object reference not set to an instance of an object.
    at new t (C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\messages.js:46:1)
    at C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:436:1
    at C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:504:1
    at Immediate.<anonymous> (C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:229:1)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
log.ts:173   ERR Object reference not set to an instance of an object.: Error: Object reference not set to an instance of an object.
    at new t (C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\messages.js:46:1)
    at C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:436:1
    at C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:504:1
    at Immediate.<anonymous> (C:\Users\Daniel\.vscode\extensions\ms-python.python-2019.3.6558\node_modules\vscode-jsonrpc\lib\main.js:229:1)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/pull/966 probably fixed this.

**Comment by jakebailey** [comment]
There's a build out now (0.2.56) which includes that PR, if you'd like to test it, @rivasd.

The preprocessing in #966 should prevent a bad value from making it to the point where it was crashing in that stack trace.
