### ISSUE TITLE
Intellisence/suggesstions stops after the following message.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#958]
@sunilkr commented on [Fri Apr 12 2019](https://github.com/Microsoft/vscode-python/issues/5225)

Issue Type: <b>Bug</b>

[2019-04-12 15:40:43.476] [exthost] [error] Error: name must not be falsy
	at Function.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:338:93)
	at new x (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:338:42)
	at new x (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:327:254)
	at O (/home/user/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:81702)
	at O (/home/user/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:81891)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/home/user/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:83:85356)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/home/user/.vscode/extensions/ms-python.python-2019.3.6558/out/client/extension.js:1:160561)

Extension version: 2019.3.6558
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4138)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.34GB (11.95GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|13%|

</details>

**Comment by jakebailey** [comment]
@sunilkr Do you have the code which caused this issue? It looks like we're sending an empty or null string for a symbol name.

**Comment by sunilkr** [comment]
I am not sure which part of the code triggered this. It is a large, and
proprietary code, so can't share.

This also seems to intermittent issue because it was resolved after
sometime (after reload may be, I am not sure).

**Comment by rvinzent** [comment]
Hi @jakebailey, this occurs for me every ~3 minutes or so breaking intellisense completely. Here's a handful of logs from my machine, again on a large proprietary codebase. I have a multi-root workspace configuration, but it doesn't seem to matter which files are being edited, the language server rarely works properly for longer than a few minutes. This error causes it to crash and it doesn't attempt to recover. There are some scripts with "undefined" variables because they are global when we run the scripts in the shell (not sure if that could be relevant):

VSCode 1.36.1
MacOS Mojave 10.14.6
Extension 2019.6.24221:

```
[2019-07-30 12:27:57.135] [exthost] [error] [ms-python.python] provider FAILED
[2019-07-30 12:27:57.135] [exthost] [error] Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:308)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:257)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:335:813)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:79946)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:84017)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:1:173205)
[2019-07-30 12:30:24.365] [exthost] [error] [ms-python.python] provider FAILED
[2019-07-30 12:30:24.365] [exthost] [error] Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:308)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:257)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:335:813)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:79946)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:84017)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:1:173205)
[2019-07-30 12:33:53.401] [exthost] [error] [ms-python.python] provider FAILED
[2019-07-30 12:33:53.401] [exthost] [error] Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:308)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:257)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:335:813)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:79946)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:84017)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:1:173205)
```

Hope this helps fix the issue :(

**Comment by jakebailey** [comment]
I'm still thinking it's just an empty name, though without a test project it's a bit hard to debug. We could add a check to prevent any symbols without names from making it out.

One thing you may be able to do is to see if closing the "outline" in VS Code fixes the issue; that's what typically makes the call, but it could also be the new-ish test explorer in the extension requesting that info.

**Comment by rvinzent** [comment]
My "outline" tab is rarely open, so almost certainly not that. I'm also a little confused what you mean by empty symbol and how that is possible in python. Are you referring to an empty variable assignment, e.g. `= 'some_value'`? I looked at the other output channels and this error is the only other relevant info:
```
[2019-07-30 16:09:19.558] [renderer3] [error] name must not be falsy: Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:308)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:347:257)
	at new b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:335:813)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:79946)
	at O (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:80114)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/rvinzent/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:84017)
	at module.exports.registerLanguageProvider.t.sendRequest.then.e (/Users/user/.vscode/extensions/ms-python.python-2019.6.24221/out/client/extension.js:1:173205)
```
The only difference as far as I can tell is that it has `renderer3` as the source
