### ISSUE TITLE
nullref in NotifyAnalysisBegins

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#967]
```
   at Microsoft.Python.Analysis.Modules.PythonModule.<>c.<NotifyAnalysisBegins>b__106_1(IScope s)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Python.Analysis.Modules.PythonModule.NotifyAnalysisBegins()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode`1 node, AsyncCountdownEvent ace, Stopwatch stopWatch, CancellationToken cancellationToken)
   --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionCont
```

**Comment by AlexanderSher** [comment]
Seen that as well
