### ISSUE TITLE
Server initialization failed. Message: Basepath argument is not fully qualified.

### ISSUE THREAD

**Issue by amliuxin** [Microsoft/python-language-server#977]
`Message: Basepath argument is not fully qualified.
Parameter name: basePath
  Code: -32000 
   at System.IO.Path.GetFullPath(String path, String basePath)
   at Microsoft.Python.LanguageServer.Implementation.Server.<InitializeAsync>b__18_1(String p)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken)`

VSCode Version: 1.33.1 (system setup)
OS: Windows_NT x64 10.0.17763
Python: v3.6.7:6ec5cf24b7
_this happened on both win10 and win7 pc after the language server updating to 0.2.56. 47 is ok but vscode auto update the language server._

**Comment by jakebailey** [comment]
Can you set `"python.trace.server": "verbose"` in your settings, and reload the editor? In the Python output panel, it will log the LSP messages, and I'm interested in seeing the initialize request given by VS Code to the language server.

This error is happening because the root is being set to a non-absolute path, which shouldn't be the case.

For example:

```
[Trace - 9:21:35 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 19820,
    "rootPath": "c:\\Users\\jabaile\\codebases\\scikit-learn",
    "rootUri": "file:///c%3A/Users/jabaile/codebases/scikit-learn",
...
```

**Comment by amliuxin** [comment]
@jakebailey , the initialize request as below, I don't know why the rootPath is null, I tried to reinstall the vscode, but got the same error message.
```[Trace - 上午10:24:33] Sending request 'initialize - (0)'.
Params: {
    "processId": 5232,
    "rootPath": null,
    "rootUri": null
}```

**Comment by jakebailey** [comment]
Are you opening a folder, or are you opening single files only without opening a folder first?

**Comment by jakebailey** [comment]
@DonJayamanne What are the conditions where the extension would be setting the root to `null`?

**Comment by amliuxin** [comment]
> Are you opening a folder, or are you opening single files only without opening a folder first?

I haven't open any folder, just create a file untitled (set the language model: python) without saving it.
