### ISSUE TITLE
Language server crashed when switching interpreters

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#978]
* Opened a workspace
* A local virtual environment was already selected
* Went and changed the interpreter to something else, 
* Then kaboom
* Reloaded VSC and then everything was ok

**Here are the logs:**

```
Starting Microsoft Python language server.
[Info  - 11:38:37 AM] GetCurrentSearchPaths /Users/don/Desktop/Development/pythonStuff/testingRepos/vscodePythonTesting/wow/venv/bin/python 
[Info  - 11:38:38 AM] Python search paths:
[Info  - 11:38:38 AM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/4i2foxe3.t0p
[Info  - 11:38:38 AM]     /Users/don/.pyenv/versions/3.7.3/lib/python3.7
[Info  - 11:38:38 AM]     /Users/don/.pyenv/versions/3.7.3/lib/python3.7/lib-dynload
[Info  - 11:38:38 AM]     /Users/don/Desktop/Development/pythonStuff/testingRepos/vscodePythonTesting/wow/venv/lib/python3.7/site-packages
[Info  - 11:38:38 AM] Configuration search paths:
[Info  - 11:38:38 AM] Microsoft Python Language Server version 0.2.56.0
[Info  - 11:38:38 AM] Initializing for /Users/don/Desktop/Development/pythonStuff/testingRepos/vscodePythonTesting/wow/venv/bin/python
[Info  - 11:40:23 AM] GetCurrentSearchPaths /Users/don/.pyenv/versions/3.6.5/bin/python 
[Info  - 11:40:23 AM] Python search paths:
[Info  - 11:40:23 AM]     /private/var/folders/ql/rq1r3gbn2jvbqpbg843ls30r0000gn/T/stmdkjyg.bvb
[Info  - 11:40:23 AM]     /Users/don/.pyenv/versions/3.6.5/lib/python3.6
[Info  - 11:40:23 AM]     /Users/don/.pyenv/versions/3.6.5/lib/python3.6/lib-dynload
[Info  - 11:40:23 AM]     /Users/don/.local/lib/python3.6/site-packages
[Info  - 11:40:23 AM]     /Users/don/.pyenv/versions/3.6.5/lib/python3.6/site-packages
[Info  - 11:40:23 AM] Configuration search paths:
[Info  - 11:40:24 AM] Microsoft Python Language Server version 0.2.56.0
[Info  - 11:40:24 AM] Initializing for /Users/don/.pyenv/versions/3.6.5/bin/python
[Error - 11:40:28 AM] Request textDocument/completion failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.Analysis.Modules.PythonModule.<>c.<NotifyAnalysisBegins>b__106_0(IScope c)
   at Microsoft.Python.Core.EnumerableExtensions.TraverseDepthFirst[T](T root, Func`2 selectChildren)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Python.Analysis.Modules.PythonModule.NotifyAnalysisBegins()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(PythonAnalyzerEntry entry, Int32 version, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(PythonAnalyzerEntry entry, CancellationToken timeoutCt, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(IPythonModule module, Int32 waitTime, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Documents.Document.GetAnalysisAsync(Uri uri, IServiceContainer services, Int32 msTimeout, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)
[Error - 11:40:33 AM] Request textDocument/completion failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.Analysis.Modules.PythonModule.<>c.<NotifyAnalysisBegins>b__106_0(IScope c)
   at Microsoft.Python.Core.EnumerableExtensions.TraverseDepthFirst[T](T root, Func`2 selectChildren)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Python.Analysis.Modules.PythonModule.NotifyAnalysisBegins()
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(PythonAnalyzerEntry entry, Int32 version, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(PythonAnalyzerEntry entry, CancellationToken timeoutCt, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(IPythonModule module, Int32 waitTime, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Documents.Document.GetAnalysisAsync(Uri uri, IServiceContainer services, Int32 msTimeout, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)
```

**Comment by jakebailey** [comment]
This is #967.
