### ISSUE TITLE
IntelliSense not working (strangely works in debug window)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#987]
@Asorie commented on [Tue Apr 16 2019](https://github.com/Microsoft/vscode-python/issues/5324)

## Environment data

- VS Code version: 1.33.1
- OS and version: Windows_NT x64 10.0.17763
- Python version: 3.7.2
- Type of virtual environment used : venv 

## Expected behaviour

Working IntelliSense and auto completion 

## Actual behaviour

![image](https://user-images.githubusercontent.com/28393962/56264579-3c7c4600-60e7-11e9-8eb3-c5381bcaee93.png)
Loads very long time, then the loading window disappears - without any suggestions.

Buf if I debug this file, intellisense is working.
![intellisense](https://user-images.githubusercontent.com/28393962/56265005-9d584e00-60e8-11e9-926b-bab558255061.png)

## Steps to reproduce:
1. seems to be a problem with my working folder. A fresh working folder with a single file and the same venv does in fact work.

## Logs
Output for `Python` in the `Output` panel

```
Starting Jedi Python language engine.
##########Linting Output - pep8##########
##########Linting Output - mypy##########
```   

Output from `Console` under the `Developer Tools` panel

```
console.ts:134 [Extension Host] Python Extension: stderr jediProxy, Error (stderr) Traceback (most recent call last):
  File "completion.py", line 622, in watch
    response = self._process_request(rq)
  File "completion.py", line 555, in _process_request
    path = self._get_top_level_module(request.get('path', ''))
  File "completion.py", line 83, in _get_top_level_module
    return cls._get_top_level_module(_path)
  File "completion.py", line 83, in _get_top_level_module
    return cls._get_top_level_module(_path)
  File "completion.py", line 83, in _get_top_level_module
    return cls._get_top_level_module(_path)
  [Previous line repeated 2991 more times]
  File "completion.py", line 81, in _get_top_level_module
    _path, _ = os.path.split(path)
  File "C:\tensorflow_anduin\lib\ntpath.py", line 184, in split
    seps = _get_bothseps(p)
  File "C:\tensorflow_anduin\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at activateOnEnter (C:\Users\halle\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:19:36)
	at context.subscriptions.push.vs.workspace.onDidChangeTextDocument.changeEvent (C:\Users\halle\.vscode\extensions\njpwerner.autodocstring-0.2.3\out\src\extension.js:13:90)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at c.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:519:227)
	at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

---

@DonJayamanne commented on [Wed Apr 17 2019](https://github.com/Microsoft/vscode-python/issues/5324#issuecomment-484193679)

Please could you try using the new `Language Server`, instructions can be found here https://github.com/Microsoft/vscode-python/issues/3977

FYI - the new language server will soon replace the existing `Jedi` (used for intellisense and the like)

---

@Asorie commented on [Wed Apr 17 2019](https://github.com/Microsoft/vscode-python/issues/5324#issuecomment-484370937)

Now it suggests only used strings
![image](https://user-images.githubusercontent.com/28393962/56340389-1079c700-61b2-11e9-9975-bbf51b0cd211.png)

Output - Python
```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.2.59.nupkg... ##########Linting Output - mypy##########
complete
Unpacking archive... done
[Info  - 08:13:48] GetCurrentSearchPaths C:\tensorflow_anduin\Scripts\python.exe 
[Info  - 08:13:48] Python search paths:
[Info  - 08:13:48]     c:\tensorflow_anduin\lib
[Info  - 08:13:48]     c:\tensorflow_anduin\scripts
[Info  - 08:13:48]     c:\program files\python37\lib
[Info  - 08:13:48]     c:\program files\python37\dlls
[Info  - 08:13:48]     c:\tensorflow_anduin
[Info  - 08:13:48]     c:\tensorflow_anduin\lib\site-packages
[Info  - 08:13:48]     c:\program files\python37
[Info  - 08:13:48]     c:\program files\python37\lib\site-packages
[Info  - 08:13:48] Configuration search paths:
[Info  - 08:13:48]     C:\tensorflow_anduin\Scripts\python37.zip
[Info  - 08:13:48]     C:\tensorflow_anduin\DLLs
[Info  - 08:13:48]     C:\tensorflow_anduin\lib
[Info  - 08:13:48]     C:\tensorflow_anduin\Scripts
[Info  - 08:13:48]     C:\Program Files\Python37\Lib
[Info  - 08:13:48]     C:\Program Files\Python37\DLLs
[Info  - 08:13:48]     C:\tensorflow_anduin
[Info  - 08:13:48]     C:\tensorflow_anduin\lib\site-packages
[Info  - 08:13:48]     C:\Program Files\Python37
[Info  - 08:13:48]     C:\Program Files\Python37\lib\site-packages
[Info  - 08:14:31] Microsoft Python Language Server version 0.2.59.0
[Info  - 08:14:31] Initializing for C:\tensorflow_anduin\Scripts\python.exe
```

**Comment by memeplex** [comment]
How the description above fits "class construction" and "arguments from `__init__`" when it's showing failure to autocomplete module `sys`? https://github.com/microsoft/python-language-server/issues/996 was closed as a cup of this one, but in fact that one actually described the issue in the subject. Being unable to autocomplete class construction arguments is a major bug, it shouldn't be under the radar because of a misleading report.

**Comment by MikhailArkhipov** [comment]
Wrong issue referenced, should have been #983

**Comment by MikhailArkhipov** [comment]
If 
```python
import sys
sys.
```
is still broken for you, feel free to reopen.
